// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v5.29.3
// source: jackpot/service/v1/payout.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PayoutService_GetPayout_FullMethodName           = "/api.jackpot.service.v1.PayoutService/GetPayout"
	PayoutService_ListPayoutsByUserID_FullMethodName = "/api.jackpot.service.v1.PayoutService/ListPayoutsByUserID"
	PayoutService_ListPayoutsByDrawID_FullMethodName = "/api.jackpot.service.v1.PayoutService/ListPayoutsByDrawID"
)

// PayoutServiceClient is the client API for PayoutService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PayoutServiceClient interface {
	GetPayout(ctx context.Context, in *GetPayoutRequest, opts ...grpc.CallOption) (*GetPayoutResponse, error)
	ListPayoutsByUserID(ctx context.Context, in *ListPayoutsByUserIDRequest, opts ...grpc.CallOption) (*ListPayoutsByUserIDResponse, error)
	ListPayoutsByDrawID(ctx context.Context, in *ListPayoutsByDrawIDRequest, opts ...grpc.CallOption) (*ListPayoutsByDrawIDResponse, error)
}

type payoutServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPayoutServiceClient(cc grpc.ClientConnInterface) PayoutServiceClient {
	return &payoutServiceClient{cc}
}

func (c *payoutServiceClient) GetPayout(ctx context.Context, in *GetPayoutRequest, opts ...grpc.CallOption) (*GetPayoutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPayoutResponse)
	err := c.cc.Invoke(ctx, PayoutService_GetPayout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *payoutServiceClient) ListPayoutsByUserID(ctx context.Context, in *ListPayoutsByUserIDRequest, opts ...grpc.CallOption) (*ListPayoutsByUserIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPayoutsByUserIDResponse)
	err := c.cc.Invoke(ctx, PayoutService_ListPayoutsByUserID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *payoutServiceClient) ListPayoutsByDrawID(ctx context.Context, in *ListPayoutsByDrawIDRequest, opts ...grpc.CallOption) (*ListPayoutsByDrawIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPayoutsByDrawIDResponse)
	err := c.cc.Invoke(ctx, PayoutService_ListPayoutsByDrawID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PayoutServiceServer is the server API for PayoutService service.
// All implementations must embed UnimplementedPayoutServiceServer
// for forward compatibility.
type PayoutServiceServer interface {
	GetPayout(context.Context, *GetPayoutRequest) (*GetPayoutResponse, error)
	ListPayoutsByUserID(context.Context, *ListPayoutsByUserIDRequest) (*ListPayoutsByUserIDResponse, error)
	ListPayoutsByDrawID(context.Context, *ListPayoutsByDrawIDRequest) (*ListPayoutsByDrawIDResponse, error)
	mustEmbedUnimplementedPayoutServiceServer()
}

// UnimplementedPayoutServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPayoutServiceServer struct{}

func (UnimplementedPayoutServiceServer) GetPayout(context.Context, *GetPayoutRequest) (*GetPayoutResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPayout not implemented")
}
func (UnimplementedPayoutServiceServer) ListPayoutsByUserID(context.Context, *ListPayoutsByUserIDRequest) (*ListPayoutsByUserIDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPayoutsByUserID not implemented")
}
func (UnimplementedPayoutServiceServer) ListPayoutsByDrawID(context.Context, *ListPayoutsByDrawIDRequest) (*ListPayoutsByDrawIDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPayoutsByDrawID not implemented")
}
func (UnimplementedPayoutServiceServer) mustEmbedUnimplementedPayoutServiceServer() {}
func (UnimplementedPayoutServiceServer) testEmbeddedByValue()                       {}

// UnsafePayoutServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PayoutServiceServer will
// result in compilation errors.
type UnsafePayoutServiceServer interface {
	mustEmbedUnimplementedPayoutServiceServer()
}

func RegisterPayoutServiceServer(s grpc.ServiceRegistrar, srv PayoutServiceServer) {
	// If the following call panics, it indicates UnimplementedPayoutServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PayoutService_ServiceDesc, srv)
}

func _PayoutService_GetPayout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPayoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayoutServiceServer).GetPayout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PayoutService_GetPayout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayoutServiceServer).GetPayout(ctx, req.(*GetPayoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PayoutService_ListPayoutsByUserID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPayoutsByUserIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayoutServiceServer).ListPayoutsByUserID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PayoutService_ListPayoutsByUserID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayoutServiceServer).ListPayoutsByUserID(ctx, req.(*ListPayoutsByUserIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PayoutService_ListPayoutsByDrawID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPayoutsByDrawIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayoutServiceServer).ListPayoutsByDrawID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PayoutService_ListPayoutsByDrawID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayoutServiceServer).ListPayoutsByDrawID(ctx, req.(*ListPayoutsByDrawIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PayoutService_ServiceDesc is the grpc.ServiceDesc for PayoutService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PayoutService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.jackpot.service.v1.PayoutService",
	HandlerType: (*PayoutServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPayout",
			Handler:    _PayoutService_GetPayout_Handler,
		},
		{
			MethodName: "ListPayoutsByUserID",
			Handler:    _PayoutService_ListPayoutsByUserID_Handler,
		},
		{
			MethodName: "ListPayoutsByDrawID",
			Handler:    _PayoutService_ListPayoutsByDrawID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "jackpot/service/v1/payout.proto",
}
