FROM golang:1.23-alpine

# 安装必要的依赖
RUN apk add --no-cache make unzip wget

# 创建工作目录
WORKDIR /tmp

# 定义版本变量
ENV PROTOC_VERSION=25.6
ENV PATH="/root/go/bin:${PATH}"
RUN wget https://github.com/protocolbuffers/protobuf/releases/download/v${PROTOC_VERSION}/protoc-${PROTOC_VERSION}-linux-x86_64.zip && \
    unzip protoc-${PROTOC_VERSION}-linux-x86_64.zip -d /usr/local && \
    chmod +x /usr/local/bin/protoc

# 安装protoc插件和工具
COPY Makefile ./
RUN make tools

RUN rm -rf *

# 设置工作目录
WORKDIR /workspace