// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.6
// source: user/service/v1/user_event.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UserEvent_Event_FullMethodName = "/api.user.service.v1.UserEvent/Event"
)

// UserEventClient is the client API for UserEvent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// User service provides authentication and user management functionality.
type UserEventClient interface {
	Event(ctx context.Context, in *EventRequest, opts ...grpc.CallOption) (*EventResponse, error)
}

type userEventClient struct {
	cc grpc.ClientConnInterface
}

func NewUserEventClient(cc grpc.ClientConnInterface) UserEventClient {
	return &userEventClient{cc}
}

func (c *userEventClient) Event(ctx context.Context, in *EventRequest, opts ...grpc.CallOption) (*EventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EventResponse)
	err := c.cc.Invoke(ctx, UserEvent_Event_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserEventServer is the server API for UserEvent service.
// All implementations must embed UnimplementedUserEventServer
// for forward compatibility.
//
// User service provides authentication and user management functionality.
type UserEventServer interface {
	Event(context.Context, *EventRequest) (*EventResponse, error)
	mustEmbedUnimplementedUserEventServer()
}

// UnimplementedUserEventServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserEventServer struct{}

func (UnimplementedUserEventServer) Event(context.Context, *EventRequest) (*EventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Event not implemented")
}
func (UnimplementedUserEventServer) mustEmbedUnimplementedUserEventServer() {}
func (UnimplementedUserEventServer) testEmbeddedByValue()                   {}

// UnsafeUserEventServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserEventServer will
// result in compilation errors.
type UnsafeUserEventServer interface {
	mustEmbedUnimplementedUserEventServer()
}

func RegisterUserEventServer(s grpc.ServiceRegistrar, srv UserEventServer) {
	// If the following call pancis, it indicates UnimplementedUserEventServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserEvent_ServiceDesc, srv)
}

func _UserEvent_Event_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserEventServer).Event(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserEvent_Event_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserEventServer).Event(ctx, req.(*EventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UserEvent_ServiceDesc is the grpc.ServiceDesc for UserEvent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserEvent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.user.service.v1.UserEvent",
	HandlerType: (*UserEventServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Event",
			Handler:    _UserEvent_Event_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user/service/v1/user_event.proto",
}
