apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config-meepo
  namespace: meepo-dev
data:
  meepo.conf: |
    # Extract base domain from subdomains
    map $ssl_server_name $base_domain {
        # Extract b.c from a.b.c
        ~^[^.]+\.([^.]+\.(?:[^.]+))$ $1;
        # Default to original domain if no match
        default $ssl_server_name;
    }

    map $ssl_server_name $target_domain {
        default meepo-app-dev.chris-dda.workers.dev;
    }

    # HTTP server for ACME HTTP-01 challenges (catch-all)
    server {
        listen 80 default_server;
        server_name
            a9game.site www.a9game.site *.a9game.site
            ngambling.tech www.ngambling.tech *.ngambling.tech;

        # ACME HTTP-01 challenge location
        location /.well-known/acme-challenge/ {
            alias /var/www/.well-known/acme-challenge/;
            try_files $uri =404;
        }

        # Redirect all other HTTP traffic to HTTPS, preserve original Host
        location / {
            return 301 https://$host$request_uri;
        }
    }

    server {
        listen 443 ssl;
        server_name
            a9game.site www.a9game.site *.a9game.site
            ngambling.tech www.ngambling.tech *.ngambling.tech;

        ssl_certificate     /etc/nginx/cert/meepo/$base_domain.pem;
        ssl_certificate_key /etc/nginx/cert/meepo/$base_domain.key;

        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers 'ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384';
        ssl_prefer_server_ciphers on;

        access_log /var/log/nginx/meepo.access.log;
        error_log  /var/log/nginx/meepo.error.log debug;

        resolver 1.1.1.1 8.8.8.8 ipv6=off;

        location ~* ^/(favicon\.ico|robots\.txt|sitemap\.xml|\.well-known/|site/.*) {
            proxy_pass https://resources.speedix.io/static/$base_domain$request_uri;
            proxy_set_header Host resources.speedix.io;
            proxy_ssl_server_name on;
            proxy_ssl_protocols TLSv1.2 TLSv1.3;

            proxy_intercept_errors on;
            error_page 404 = @fallback_static;

            add_header Cache-Control "public, max-age=3600";
        }

        location ^~ /static/ {
        #proxy_pass https://resources.speedix.io$request_uri;
        #proxy_set_header Host resources.speedix.io;
        proxy_pass https://gares.cc$request_uri;
        proxy_set_header Host gares.cc;
            proxy_ssl_server_name on;
            proxy_ssl_protocols TLSv1.2 TLSv1.3;

            add_header Cache-Control "public, max-age=300";
        }

        location / {
            proxy_pass https://$target_domain;
            proxy_set_header Host $target_domain;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_ssl_server_name on;
            proxy_ssl_protocols TLSv1.2 TLSv1.3;
        }

        location @fallback_static {
            proxy_pass https://$target_domain$request_uri;
            proxy_set_header Host $target_domain;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_ssl_server_name on;
            proxy_ssl_protocols TLSv1.2 TLSv1.3;
        }
    }
  meepo-bo.conf: |
    # Extract base domain from subdomains for backoffice
    map $ssl_server_name $base_domain {
        # Extract b.c from a.b.c
        ~^[^.]+\.([^.]+\.(?:[^.]+))$ $1;
        # Default to original domain if no match
        default $ssl_server_name;
    }

    # HTTP server for ACME HTTP-01 challenges (catch-all)
    server {
        listen 80;
        server_name
            meepo.site www.meepo.site *.meepo.site;

        # ACME HTTP-01 challenge location
        location /.well-known/acme-challenge/ {
            alias /var/www/.well-known/acme-challenge/;
            try_files $uri =404;
        }

        # Redirect all other HTTP traffic to HTTPS, preserve original Host
        location / {
            return 301 https://$host$request_uri;
        }
    }

    server {
        listen 443 ssl;
        server_name
            meepo.site www.meepo.site *.meepo.site
            meepoadmin.site www.meepoadmin.site *.meepoadmin.site;
        
        ssl_certificate     /etc/nginx/cert/meepo/$base_domain.pem;
        ssl_certificate_key /etc/nginx/cert/meepo/$base_domain.key;

        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers 'ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384';
        ssl_prefer_server_ciphers on;

        access_log /var/log/nginx/meepo-bo.access.log;
        error_log  /var/log/nginx/meepo-bo.error.log debug;

        resolver 1.1.1.1 8.8.8.8 ipv6=off;

        location ^~ /static/ {
            #proxy_pass https://resources.speedix.io$request_uri;
            #proxy_set_header Host resources.speedix.io;
            proxy_pass https://gares.cc$request_uri;
            proxy_set_header Host gares.cc;
            proxy_ssl_server_name on;
            proxy_ssl_protocols TLSv1.2 TLSv1.3;

            add_header Cache-Control "public, max-age=300";
        }

        location / {
            proxy_pass https://meepo-backoffice-dev.chris-dda.workers.dev;
            proxy_set_header Host meepo-backoffice-dev.chris-dda.workers.dev;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_ssl_server_name on;
            proxy_ssl_protocols TLSv1.2 TLSv1.3;
        }
    }
