// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.6
// source: backoffice/service/v1/backoffice_review.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BackofficeReview_ListWithdrawReviewTickets_FullMethodName = "/api.backoffice.service.v1.BackofficeReview/ListWithdrawReviewTickets"
	BackofficeReview_ReviewTicket_FullMethodName              = "/api.backoffice.service.v1.BackofficeReview/ReviewTicket"
)

// BackofficeReviewClient is the client API for BackofficeReview service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BackofficeReviewClient interface {
	ListWithdrawReviewTickets(ctx context.Context, in *ListWithdrawReviewTicketsRequest, opts ...grpc.CallOption) (*ListWithdrawReviewTicketsResponse, error)
	ReviewTicket(ctx context.Context, in *ReviewTicketRequest, opts ...grpc.CallOption) (*ReviewTicketResponse, error)
}

type backofficeReviewClient struct {
	cc grpc.ClientConnInterface
}

func NewBackofficeReviewClient(cc grpc.ClientConnInterface) BackofficeReviewClient {
	return &backofficeReviewClient{cc}
}

func (c *backofficeReviewClient) ListWithdrawReviewTickets(ctx context.Context, in *ListWithdrawReviewTicketsRequest, opts ...grpc.CallOption) (*ListWithdrawReviewTicketsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListWithdrawReviewTicketsResponse)
	err := c.cc.Invoke(ctx, BackofficeReview_ListWithdrawReviewTickets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backofficeReviewClient) ReviewTicket(ctx context.Context, in *ReviewTicketRequest, opts ...grpc.CallOption) (*ReviewTicketResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReviewTicketResponse)
	err := c.cc.Invoke(ctx, BackofficeReview_ReviewTicket_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BackofficeReviewServer is the server API for BackofficeReview service.
// All implementations must embed UnimplementedBackofficeReviewServer
// for forward compatibility.
type BackofficeReviewServer interface {
	ListWithdrawReviewTickets(context.Context, *ListWithdrawReviewTicketsRequest) (*ListWithdrawReviewTicketsResponse, error)
	ReviewTicket(context.Context, *ReviewTicketRequest) (*ReviewTicketResponse, error)
	mustEmbedUnimplementedBackofficeReviewServer()
}

// UnimplementedBackofficeReviewServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBackofficeReviewServer struct{}

func (UnimplementedBackofficeReviewServer) ListWithdrawReviewTickets(context.Context, *ListWithdrawReviewTicketsRequest) (*ListWithdrawReviewTicketsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListWithdrawReviewTickets not implemented")
}
func (UnimplementedBackofficeReviewServer) ReviewTicket(context.Context, *ReviewTicketRequest) (*ReviewTicketResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReviewTicket not implemented")
}
func (UnimplementedBackofficeReviewServer) mustEmbedUnimplementedBackofficeReviewServer() {}
func (UnimplementedBackofficeReviewServer) testEmbeddedByValue()                          {}

// UnsafeBackofficeReviewServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BackofficeReviewServer will
// result in compilation errors.
type UnsafeBackofficeReviewServer interface {
	mustEmbedUnimplementedBackofficeReviewServer()
}

func RegisterBackofficeReviewServer(s grpc.ServiceRegistrar, srv BackofficeReviewServer) {
	// If the following call pancis, it indicates UnimplementedBackofficeReviewServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BackofficeReview_ServiceDesc, srv)
}

func _BackofficeReview_ListWithdrawReviewTickets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWithdrawReviewTicketsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackofficeReviewServer).ListWithdrawReviewTickets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BackofficeReview_ListWithdrawReviewTickets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackofficeReviewServer).ListWithdrawReviewTickets(ctx, req.(*ListWithdrawReviewTicketsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackofficeReview_ReviewTicket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReviewTicketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackofficeReviewServer).ReviewTicket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BackofficeReview_ReviewTicket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackofficeReviewServer).ReviewTicket(ctx, req.(*ReviewTicketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BackofficeReview_ServiceDesc is the grpc.ServiceDesc for BackofficeReview service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BackofficeReview_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.backoffice.service.v1.BackofficeReview",
	HandlerType: (*BackofficeReviewServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListWithdrawReviewTickets",
			Handler:    _BackofficeReview_ListWithdrawReviewTickets_Handler,
		},
		{
			MethodName: "ReviewTicket",
			Handler:    _BackofficeReview_ReviewTicket_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "backoffice/service/v1/backoffice_review.proto",
}
