// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: backoffice/service/v1/backoffice_vip.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on VipSetting with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *VipSetting) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on VipSetting with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in VipSettingMultiError, or
// nil if none found.
func (m *VipSetting) ValidateAll() error {
	return m.validate(true)
}

func (m *VipSetting) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for SystemOperatorId

	// no validation rules for RetailerOperatorId

	// no validation rules for CompanyOperatorId

	// no validation rules for OperatorId

	// no validation rules for BaseCurrency

	// no validation rules for DisplayRule

	// no validation rules for RewardsSlider

	// no validation rules for FollowParent

	// no validation rules for Enabled

	// no validation rules for UpgradePayoutType

	// no validation rules for RakebackInstantPayoutType

	// no validation rules for RakebackDailyPayoutType

	// no validation rules for WeeklyRewardPayoutType

	// no validation rules for MonthlyRewardPayoutType

	// no validation rules for DepositXpRate

	// no validation rules for WageringXpRate

	// no validation rules for MaxHouseEdgeLimitPercent

	// no validation rules for StandardXpMultiplier

	// no validation rules for Timezone

	// no validation rules for DailyIssueAt

	// no validation rules for WeeklyIssueDow

	// no validation rules for WeeklyIssueAt

	// no validation rules for MonthlyIssueDom

	// no validation rules for MonthlyIssueAt

	// no validation rules for CreatedAt

	// no validation rules for UpdatedAt

	if len(errors) > 0 {
		return VipSettingMultiError(errors)
	}

	return nil
}

// VipSettingMultiError is an error wrapping multiple validation errors
// returned by VipSetting.ValidateAll() if the designated constraints aren't met.
type VipSettingMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m VipSettingMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m VipSettingMultiError) AllErrors() []error { return m }

// VipSettingValidationError is the validation error returned by
// VipSetting.Validate if the designated constraints aren't met.
type VipSettingValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e VipSettingValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e VipSettingValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e VipSettingValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e VipSettingValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e VipSettingValidationError) ErrorName() string { return "VipSettingValidationError" }

// Error satisfies the builtin error interface
func (e VipSettingValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sVipSetting.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = VipSettingValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = VipSettingValidationError{}

// Validate checks the field values on GetVipSettingRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetVipSettingRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetVipSettingRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetVipSettingRequestMultiError, or nil if none found.
func (m *GetVipSettingRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetVipSettingRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetTargetOperatorContext()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetVipSettingRequestValidationError{
					field:  "TargetOperatorContext",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetVipSettingRequestValidationError{
					field:  "TargetOperatorContext",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetTargetOperatorContext()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetVipSettingRequestValidationError{
				field:  "TargetOperatorContext",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for Currency

	if len(errors) > 0 {
		return GetVipSettingRequestMultiError(errors)
	}

	return nil
}

// GetVipSettingRequestMultiError is an error wrapping multiple validation
// errors returned by GetVipSettingRequest.ValidateAll() if the designated
// constraints aren't met.
type GetVipSettingRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetVipSettingRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetVipSettingRequestMultiError) AllErrors() []error { return m }

// GetVipSettingRequestValidationError is the validation error returned by
// GetVipSettingRequest.Validate if the designated constraints aren't met.
type GetVipSettingRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetVipSettingRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetVipSettingRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetVipSettingRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetVipSettingRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetVipSettingRequestValidationError) ErrorName() string {
	return "GetVipSettingRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetVipSettingRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetVipSettingRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetVipSettingRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetVipSettingRequestValidationError{}

// Validate checks the field values on GetVipSettingResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetVipSettingResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetVipSettingResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetVipSettingResponseMultiError, or nil if none found.
func (m *GetVipSettingResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetVipSettingResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetDefaultSetting()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetVipSettingResponseValidationError{
					field:  "DefaultSetting",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetVipSettingResponseValidationError{
					field:  "DefaultSetting",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetDefaultSetting()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetVipSettingResponseValidationError{
				field:  "DefaultSetting",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetCustomSetting()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetVipSettingResponseValidationError{
					field:  "CustomSetting",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetVipSettingResponseValidationError{
					field:  "CustomSetting",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCustomSetting()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetVipSettingResponseValidationError{
				field:  "CustomSetting",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for FollowParent

	if all {
		switch v := interface{}(m.GetCustomOperatorContext()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetVipSettingResponseValidationError{
					field:  "CustomOperatorContext",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetVipSettingResponseValidationError{
					field:  "CustomOperatorContext",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCustomOperatorContext()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetVipSettingResponseValidationError{
				field:  "CustomOperatorContext",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetInheritedOperatorContext()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetVipSettingResponseValidationError{
					field:  "InheritedOperatorContext",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetVipSettingResponseValidationError{
					field:  "InheritedOperatorContext",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetInheritedOperatorContext()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetVipSettingResponseValidationError{
				field:  "InheritedOperatorContext",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for InheritedFromOperatorName

	for idx, item := range m.GetDefaultTemplates() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GetVipSettingResponseValidationError{
						field:  fmt.Sprintf("DefaultTemplates[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GetVipSettingResponseValidationError{
						field:  fmt.Sprintf("DefaultTemplates[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GetVipSettingResponseValidationError{
					field:  fmt.Sprintf("DefaultTemplates[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	for idx, item := range m.GetCustomTemplates() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GetVipSettingResponseValidationError{
						field:  fmt.Sprintf("CustomTemplates[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GetVipSettingResponseValidationError{
						field:  fmt.Sprintf("CustomTemplates[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GetVipSettingResponseValidationError{
					field:  fmt.Sprintf("CustomTemplates[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return GetVipSettingResponseMultiError(errors)
	}

	return nil
}

// GetVipSettingResponseMultiError is an error wrapping multiple validation
// errors returned by GetVipSettingResponse.ValidateAll() if the designated
// constraints aren't met.
type GetVipSettingResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetVipSettingResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetVipSettingResponseMultiError) AllErrors() []error { return m }

// GetVipSettingResponseValidationError is the validation error returned by
// GetVipSettingResponse.Validate if the designated constraints aren't met.
type GetVipSettingResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetVipSettingResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetVipSettingResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetVipSettingResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetVipSettingResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetVipSettingResponseValidationError) ErrorName() string {
	return "GetVipSettingResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetVipSettingResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetVipSettingResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetVipSettingResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetVipSettingResponseValidationError{}

// Validate checks the field values on UpdateVipSettingRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateVipSettingRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateVipSettingRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateVipSettingRequestMultiError, or nil if none found.
func (m *UpdateVipSettingRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateVipSettingRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetTargetOperatorContext()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UpdateVipSettingRequestValidationError{
					field:  "TargetOperatorContext",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UpdateVipSettingRequestValidationError{
					field:  "TargetOperatorContext",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetTargetOperatorContext()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UpdateVipSettingRequestValidationError{
				field:  "TargetOperatorContext",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetSetting()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UpdateVipSettingRequestValidationError{
					field:  "Setting",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UpdateVipSettingRequestValidationError{
					field:  "Setting",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetSetting()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UpdateVipSettingRequestValidationError{
				field:  "Setting",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return UpdateVipSettingRequestMultiError(errors)
	}

	return nil
}

// UpdateVipSettingRequestMultiError is an error wrapping multiple validation
// errors returned by UpdateVipSettingRequest.ValidateAll() if the designated
// constraints aren't met.
type UpdateVipSettingRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateVipSettingRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateVipSettingRequestMultiError) AllErrors() []error { return m }

// UpdateVipSettingRequestValidationError is the validation error returned by
// UpdateVipSettingRequest.Validate if the designated constraints aren't met.
type UpdateVipSettingRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateVipSettingRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateVipSettingRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateVipSettingRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateVipSettingRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateVipSettingRequestValidationError) ErrorName() string {
	return "UpdateVipSettingRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateVipSettingRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateVipSettingRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateVipSettingRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateVipSettingRequestValidationError{}

// Validate checks the field values on UpdateVipSettingResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateVipSettingResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateVipSettingResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateVipSettingResponseMultiError, or nil if none found.
func (m *UpdateVipSettingResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateVipSettingResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return UpdateVipSettingResponseMultiError(errors)
	}

	return nil
}

// UpdateVipSettingResponseMultiError is an error wrapping multiple validation
// errors returned by UpdateVipSettingResponse.ValidateAll() if the designated
// constraints aren't met.
type UpdateVipSettingResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateVipSettingResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateVipSettingResponseMultiError) AllErrors() []error { return m }

// UpdateVipSettingResponseValidationError is the validation error returned by
// UpdateVipSettingResponse.Validate if the designated constraints aren't met.
type UpdateVipSettingResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateVipSettingResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateVipSettingResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateVipSettingResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateVipSettingResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateVipSettingResponseValidationError) ErrorName() string {
	return "UpdateVipSettingResponseValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateVipSettingResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateVipSettingResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateVipSettingResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateVipSettingResponseValidationError{}

// Validate checks the field values on VipLevelConfigTemplate with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *VipLevelConfigTemplate) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on VipLevelConfigTemplate with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// VipLevelConfigTemplateMultiError, or nil if none found.
func (m *VipLevelConfigTemplate) ValidateAll() error {
	return m.validate(true)
}

func (m *VipLevelConfigTemplate) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for SystemOperatorId

	// no validation rules for RetailerOperatorId

	// no validation rules for CompanyOperatorId

	// no validation rules for OperatorId

	// no validation rules for Name

	// no validation rules for StartLevel

	// no validation rules for EndLevel

	// no validation rules for BaseLevelUpgradeXp

	// no validation rules for IncrLevelUpgradeXp

	// no validation rules for BaseUpgradeRewardAmt

	// no validation rules for IncrUpgradeRewardAmt

	// no validation rules for UpgradeRewardWageringX

	// no validation rules for XpLossEnabled

	// no validation rules for WeeklyXpLoss

	// no validation rules for MonthlyXpLoss

	// no validation rules for RakebackInstantEnabled

	// no validation rules for RakebackInstantRate

	// no validation rules for RakebackInstantReq

	// no validation rules for RakebackDailyEnabled

	// no validation rules for RakebackDailyRate

	// no validation rules for RakebackDailyReq

	// no validation rules for WeeklyRewardEnabled

	// no validation rules for WeeklyFixedRewardAmt

	// no validation rules for WeeklyTurnoverRate

	// no validation rules for WeeklyNetLossAmt

	// no validation rules for WeeklyAdjustRangePct

	// no validation rules for WeeklyActiveDaysReward

	// no validation rules for WeeklyWageringReq

	// no validation rules for MonthlyRewardEnabled

	// no validation rules for MonthlyFixedRewardAmt

	// no validation rules for MonthlyTurnoverRate

	// no validation rules for MonthlyNetLossAmt

	// no validation rules for MonthlyAdjustRangePct

	// no validation rules for MonthlyActiveDaysReward

	// no validation rules for MonthlyWageringReq

	// no validation rules for CreatedAt

	// no validation rules for UpdatedAt

	if len(errors) > 0 {
		return VipLevelConfigTemplateMultiError(errors)
	}

	return nil
}

// VipLevelConfigTemplateMultiError is an error wrapping multiple validation
// errors returned by VipLevelConfigTemplate.ValidateAll() if the designated
// constraints aren't met.
type VipLevelConfigTemplateMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m VipLevelConfigTemplateMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m VipLevelConfigTemplateMultiError) AllErrors() []error { return m }

// VipLevelConfigTemplateValidationError is the validation error returned by
// VipLevelConfigTemplate.Validate if the designated constraints aren't met.
type VipLevelConfigTemplateValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e VipLevelConfigTemplateValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e VipLevelConfigTemplateValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e VipLevelConfigTemplateValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e VipLevelConfigTemplateValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e VipLevelConfigTemplateValidationError) ErrorName() string {
	return "VipLevelConfigTemplateValidationError"
}

// Error satisfies the builtin error interface
func (e VipLevelConfigTemplateValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sVipLevelConfigTemplate.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = VipLevelConfigTemplateValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = VipLevelConfigTemplateValidationError{}

// Validate checks the field values on GetVipLevelConfigTemplateRequest with
// the rules defined in the proto definition for this message. If any rules
// are violated, the first error encountered is returned, or nil if there are
// no violations.
func (m *GetVipLevelConfigTemplateRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetVipLevelConfigTemplateRequest with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// GetVipLevelConfigTemplateRequestMultiError, or nil if none found.
func (m *GetVipLevelConfigTemplateRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetVipLevelConfigTemplateRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetTargetOperatorContext()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetVipLevelConfigTemplateRequestValidationError{
					field:  "TargetOperatorContext",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetVipLevelConfigTemplateRequestValidationError{
					field:  "TargetOperatorContext",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetTargetOperatorContext()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetVipLevelConfigTemplateRequestValidationError{
				field:  "TargetOperatorContext",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for TemplateId

	if len(errors) > 0 {
		return GetVipLevelConfigTemplateRequestMultiError(errors)
	}

	return nil
}

// GetVipLevelConfigTemplateRequestMultiError is an error wrapping multiple
// validation errors returned by
// GetVipLevelConfigTemplateRequest.ValidateAll() if the designated
// constraints aren't met.
type GetVipLevelConfigTemplateRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetVipLevelConfigTemplateRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetVipLevelConfigTemplateRequestMultiError) AllErrors() []error { return m }

// GetVipLevelConfigTemplateRequestValidationError is the validation error
// returned by GetVipLevelConfigTemplateRequest.Validate if the designated
// constraints aren't met.
type GetVipLevelConfigTemplateRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetVipLevelConfigTemplateRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetVipLevelConfigTemplateRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetVipLevelConfigTemplateRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetVipLevelConfigTemplateRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetVipLevelConfigTemplateRequestValidationError) ErrorName() string {
	return "GetVipLevelConfigTemplateRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetVipLevelConfigTemplateRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetVipLevelConfigTemplateRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetVipLevelConfigTemplateRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetVipLevelConfigTemplateRequestValidationError{}

// Validate checks the field values on GetVipLevelConfigTemplateResponse with
// the rules defined in the proto definition for this message. If any rules
// are violated, the first error encountered is returned, or nil if there are
// no violations.
func (m *GetVipLevelConfigTemplateResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetVipLevelConfigTemplateResponse
// with the rules defined in the proto definition for this message. If any
// rules are violated, the result is a list of violation errors wrapped in
// GetVipLevelConfigTemplateResponseMultiError, or nil if none found.
func (m *GetVipLevelConfigTemplateResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetVipLevelConfigTemplateResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetTemplate()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetVipLevelConfigTemplateResponseValidationError{
					field:  "Template",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetVipLevelConfigTemplateResponseValidationError{
					field:  "Template",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetTemplate()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetVipLevelConfigTemplateResponseValidationError{
				field:  "Template",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetVipLevelConfigTemplateResponseMultiError(errors)
	}

	return nil
}

// GetVipLevelConfigTemplateResponseMultiError is an error wrapping multiple
// validation errors returned by
// GetVipLevelConfigTemplateResponse.ValidateAll() if the designated
// constraints aren't met.
type GetVipLevelConfigTemplateResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetVipLevelConfigTemplateResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetVipLevelConfigTemplateResponseMultiError) AllErrors() []error { return m }

// GetVipLevelConfigTemplateResponseValidationError is the validation error
// returned by GetVipLevelConfigTemplateResponse.Validate if the designated
// constraints aren't met.
type GetVipLevelConfigTemplateResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetVipLevelConfigTemplateResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetVipLevelConfigTemplateResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetVipLevelConfigTemplateResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetVipLevelConfigTemplateResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetVipLevelConfigTemplateResponseValidationError) ErrorName() string {
	return "GetVipLevelConfigTemplateResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetVipLevelConfigTemplateResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetVipLevelConfigTemplateResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetVipLevelConfigTemplateResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetVipLevelConfigTemplateResponseValidationError{}

// Validate checks the field values on CreateVipLevelConfigTemplateRequest with
// the rules defined in the proto definition for this message. If any rules
// are violated, the first error encountered is returned, or nil if there are
// no violations.
func (m *CreateVipLevelConfigTemplateRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateVipLevelConfigTemplateRequest
// with the rules defined in the proto definition for this message. If any
// rules are violated, the result is a list of violation errors wrapped in
// CreateVipLevelConfigTemplateRequestMultiError, or nil if none found.
func (m *CreateVipLevelConfigTemplateRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateVipLevelConfigTemplateRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetTargetOperatorContext()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CreateVipLevelConfigTemplateRequestValidationError{
					field:  "TargetOperatorContext",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CreateVipLevelConfigTemplateRequestValidationError{
					field:  "TargetOperatorContext",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetTargetOperatorContext()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreateVipLevelConfigTemplateRequestValidationError{
				field:  "TargetOperatorContext",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for SettingId

	if all {
		switch v := interface{}(m.GetTemplate()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CreateVipLevelConfigTemplateRequestValidationError{
					field:  "Template",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CreateVipLevelConfigTemplateRequestValidationError{
					field:  "Template",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetTemplate()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreateVipLevelConfigTemplateRequestValidationError{
				field:  "Template",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return CreateVipLevelConfigTemplateRequestMultiError(errors)
	}

	return nil
}

// CreateVipLevelConfigTemplateRequestMultiError is an error wrapping multiple
// validation errors returned by
// CreateVipLevelConfigTemplateRequest.ValidateAll() if the designated
// constraints aren't met.
type CreateVipLevelConfigTemplateRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateVipLevelConfigTemplateRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateVipLevelConfigTemplateRequestMultiError) AllErrors() []error { return m }

// CreateVipLevelConfigTemplateRequestValidationError is the validation error
// returned by CreateVipLevelConfigTemplateRequest.Validate if the designated
// constraints aren't met.
type CreateVipLevelConfigTemplateRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateVipLevelConfigTemplateRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateVipLevelConfigTemplateRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateVipLevelConfigTemplateRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateVipLevelConfigTemplateRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateVipLevelConfigTemplateRequestValidationError) ErrorName() string {
	return "CreateVipLevelConfigTemplateRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateVipLevelConfigTemplateRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateVipLevelConfigTemplateRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateVipLevelConfigTemplateRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateVipLevelConfigTemplateRequestValidationError{}

// Validate checks the field values on CreateVipLevelConfigTemplateResponse
// with the rules defined in the proto definition for this message. If any
// rules are violated, the first error encountered is returned, or nil if
// there are no violations.
func (m *CreateVipLevelConfigTemplateResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateVipLevelConfigTemplateResponse
// with the rules defined in the proto definition for this message. If any
// rules are violated, the result is a list of violation errors wrapped in
// CreateVipLevelConfigTemplateResponseMultiError, or nil if none found.
func (m *CreateVipLevelConfigTemplateResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateVipLevelConfigTemplateResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetTemplate()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CreateVipLevelConfigTemplateResponseValidationError{
					field:  "Template",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CreateVipLevelConfigTemplateResponseValidationError{
					field:  "Template",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetTemplate()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreateVipLevelConfigTemplateResponseValidationError{
				field:  "Template",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return CreateVipLevelConfigTemplateResponseMultiError(errors)
	}

	return nil
}

// CreateVipLevelConfigTemplateResponseMultiError is an error wrapping multiple
// validation errors returned by
// CreateVipLevelConfigTemplateResponse.ValidateAll() if the designated
// constraints aren't met.
type CreateVipLevelConfigTemplateResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateVipLevelConfigTemplateResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateVipLevelConfigTemplateResponseMultiError) AllErrors() []error { return m }

// CreateVipLevelConfigTemplateResponseValidationError is the validation error
// returned by CreateVipLevelConfigTemplateResponse.Validate if the designated
// constraints aren't met.
type CreateVipLevelConfigTemplateResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateVipLevelConfigTemplateResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateVipLevelConfigTemplateResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateVipLevelConfigTemplateResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateVipLevelConfigTemplateResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateVipLevelConfigTemplateResponseValidationError) ErrorName() string {
	return "CreateVipLevelConfigTemplateResponseValidationError"
}

// Error satisfies the builtin error interface
func (e CreateVipLevelConfigTemplateResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateVipLevelConfigTemplateResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateVipLevelConfigTemplateResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateVipLevelConfigTemplateResponseValidationError{}

// Validate checks the field values on UpdateVipLevelConfigTemplateRequest with
// the rules defined in the proto definition for this message. If any rules
// are violated, the first error encountered is returned, or nil if there are
// no violations.
func (m *UpdateVipLevelConfigTemplateRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateVipLevelConfigTemplateRequest
// with the rules defined in the proto definition for this message. If any
// rules are violated, the result is a list of violation errors wrapped in
// UpdateVipLevelConfigTemplateRequestMultiError, or nil if none found.
func (m *UpdateVipLevelConfigTemplateRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateVipLevelConfigTemplateRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetTargetOperatorContext()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UpdateVipLevelConfigTemplateRequestValidationError{
					field:  "TargetOperatorContext",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UpdateVipLevelConfigTemplateRequestValidationError{
					field:  "TargetOperatorContext",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetTargetOperatorContext()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UpdateVipLevelConfigTemplateRequestValidationError{
				field:  "TargetOperatorContext",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetTemplate()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UpdateVipLevelConfigTemplateRequestValidationError{
					field:  "Template",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UpdateVipLevelConfigTemplateRequestValidationError{
					field:  "Template",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetTemplate()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UpdateVipLevelConfigTemplateRequestValidationError{
				field:  "Template",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return UpdateVipLevelConfigTemplateRequestMultiError(errors)
	}

	return nil
}

// UpdateVipLevelConfigTemplateRequestMultiError is an error wrapping multiple
// validation errors returned by
// UpdateVipLevelConfigTemplateRequest.ValidateAll() if the designated
// constraints aren't met.
type UpdateVipLevelConfigTemplateRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateVipLevelConfigTemplateRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateVipLevelConfigTemplateRequestMultiError) AllErrors() []error { return m }

// UpdateVipLevelConfigTemplateRequestValidationError is the validation error
// returned by UpdateVipLevelConfigTemplateRequest.Validate if the designated
// constraints aren't met.
type UpdateVipLevelConfigTemplateRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateVipLevelConfigTemplateRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateVipLevelConfigTemplateRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateVipLevelConfigTemplateRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateVipLevelConfigTemplateRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateVipLevelConfigTemplateRequestValidationError) ErrorName() string {
	return "UpdateVipLevelConfigTemplateRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateVipLevelConfigTemplateRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateVipLevelConfigTemplateRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateVipLevelConfigTemplateRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateVipLevelConfigTemplateRequestValidationError{}

// Validate checks the field values on UpdateVipLevelConfigTemplateResponse
// with the rules defined in the proto definition for this message. If any
// rules are violated, the first error encountered is returned, or nil if
// there are no violations.
func (m *UpdateVipLevelConfigTemplateResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateVipLevelConfigTemplateResponse
// with the rules defined in the proto definition for this message. If any
// rules are violated, the result is a list of violation errors wrapped in
// UpdateVipLevelConfigTemplateResponseMultiError, or nil if none found.
func (m *UpdateVipLevelConfigTemplateResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateVipLevelConfigTemplateResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return UpdateVipLevelConfigTemplateResponseMultiError(errors)
	}

	return nil
}

// UpdateVipLevelConfigTemplateResponseMultiError is an error wrapping multiple
// validation errors returned by
// UpdateVipLevelConfigTemplateResponse.ValidateAll() if the designated
// constraints aren't met.
type UpdateVipLevelConfigTemplateResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateVipLevelConfigTemplateResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateVipLevelConfigTemplateResponseMultiError) AllErrors() []error { return m }

// UpdateVipLevelConfigTemplateResponseValidationError is the validation error
// returned by UpdateVipLevelConfigTemplateResponse.Validate if the designated
// constraints aren't met.
type UpdateVipLevelConfigTemplateResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateVipLevelConfigTemplateResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateVipLevelConfigTemplateResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateVipLevelConfigTemplateResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateVipLevelConfigTemplateResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateVipLevelConfigTemplateResponseValidationError) ErrorName() string {
	return "UpdateVipLevelConfigTemplateResponseValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateVipLevelConfigTemplateResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateVipLevelConfigTemplateResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateVipLevelConfigTemplateResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateVipLevelConfigTemplateResponseValidationError{}

// Validate checks the field values on DeleteVipLevelConfigTemplateRequest with
// the rules defined in the proto definition for this message. If any rules
// are violated, the first error encountered is returned, or nil if there are
// no violations.
func (m *DeleteVipLevelConfigTemplateRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteVipLevelConfigTemplateRequest
// with the rules defined in the proto definition for this message. If any
// rules are violated, the result is a list of violation errors wrapped in
// DeleteVipLevelConfigTemplateRequestMultiError, or nil if none found.
func (m *DeleteVipLevelConfigTemplateRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteVipLevelConfigTemplateRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetTargetOperatorContext()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, DeleteVipLevelConfigTemplateRequestValidationError{
					field:  "TargetOperatorContext",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, DeleteVipLevelConfigTemplateRequestValidationError{
					field:  "TargetOperatorContext",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetTargetOperatorContext()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return DeleteVipLevelConfigTemplateRequestValidationError{
				field:  "TargetOperatorContext",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for TemplateId

	if len(errors) > 0 {
		return DeleteVipLevelConfigTemplateRequestMultiError(errors)
	}

	return nil
}

// DeleteVipLevelConfigTemplateRequestMultiError is an error wrapping multiple
// validation errors returned by
// DeleteVipLevelConfigTemplateRequest.ValidateAll() if the designated
// constraints aren't met.
type DeleteVipLevelConfigTemplateRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteVipLevelConfigTemplateRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteVipLevelConfigTemplateRequestMultiError) AllErrors() []error { return m }

// DeleteVipLevelConfigTemplateRequestValidationError is the validation error
// returned by DeleteVipLevelConfigTemplateRequest.Validate if the designated
// constraints aren't met.
type DeleteVipLevelConfigTemplateRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteVipLevelConfigTemplateRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteVipLevelConfigTemplateRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteVipLevelConfigTemplateRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteVipLevelConfigTemplateRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteVipLevelConfigTemplateRequestValidationError) ErrorName() string {
	return "DeleteVipLevelConfigTemplateRequestValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteVipLevelConfigTemplateRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteVipLevelConfigTemplateRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteVipLevelConfigTemplateRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteVipLevelConfigTemplateRequestValidationError{}

// Validate checks the field values on DeleteVipLevelConfigTemplateResponse
// with the rules defined in the proto definition for this message. If any
// rules are violated, the first error encountered is returned, or nil if
// there are no violations.
func (m *DeleteVipLevelConfigTemplateResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteVipLevelConfigTemplateResponse
// with the rules defined in the proto definition for this message. If any
// rules are violated, the result is a list of violation errors wrapped in
// DeleteVipLevelConfigTemplateResponseMultiError, or nil if none found.
func (m *DeleteVipLevelConfigTemplateResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteVipLevelConfigTemplateResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return DeleteVipLevelConfigTemplateResponseMultiError(errors)
	}

	return nil
}

// DeleteVipLevelConfigTemplateResponseMultiError is an error wrapping multiple
// validation errors returned by
// DeleteVipLevelConfigTemplateResponse.ValidateAll() if the designated
// constraints aren't met.
type DeleteVipLevelConfigTemplateResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteVipLevelConfigTemplateResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteVipLevelConfigTemplateResponseMultiError) AllErrors() []error { return m }

// DeleteVipLevelConfigTemplateResponseValidationError is the validation error
// returned by DeleteVipLevelConfigTemplateResponse.Validate if the designated
// constraints aren't met.
type DeleteVipLevelConfigTemplateResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteVipLevelConfigTemplateResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteVipLevelConfigTemplateResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteVipLevelConfigTemplateResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteVipLevelConfigTemplateResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteVipLevelConfigTemplateResponseValidationError) ErrorName() string {
	return "DeleteVipLevelConfigTemplateResponseValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteVipLevelConfigTemplateResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteVipLevelConfigTemplateResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteVipLevelConfigTemplateResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteVipLevelConfigTemplateResponseValidationError{}

// Validate checks the field values on GetVipConfigRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetVipConfigRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetVipConfigRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetVipConfigRequestMultiError, or nil if none found.
func (m *GetVipConfigRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetVipConfigRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetTargetOperatorContext()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetVipConfigRequestValidationError{
					field:  "TargetOperatorContext",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetVipConfigRequestValidationError{
					field:  "TargetOperatorContext",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetTargetOperatorContext()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetVipConfigRequestValidationError{
				field:  "TargetOperatorContext",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetVipConfigRequestMultiError(errors)
	}

	return nil
}

// GetVipConfigRequestMultiError is an error wrapping multiple validation
// errors returned by GetVipConfigRequest.ValidateAll() if the designated
// constraints aren't met.
type GetVipConfigRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetVipConfigRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetVipConfigRequestMultiError) AllErrors() []error { return m }

// GetVipConfigRequestValidationError is the validation error returned by
// GetVipConfigRequest.Validate if the designated constraints aren't met.
type GetVipConfigRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetVipConfigRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetVipConfigRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetVipConfigRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetVipConfigRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetVipConfigRequestValidationError) ErrorName() string {
	return "GetVipConfigRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetVipConfigRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetVipConfigRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetVipConfigRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetVipConfigRequestValidationError{}

// Validate checks the field values on VipConfig with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *VipConfig) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on VipConfig with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in VipConfigMultiError, or nil
// if none found.
func (m *VipConfig) ValidateAll() error {
	return m.validate(true)
}

func (m *VipConfig) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for SystemOperatorId

	// no validation rules for RetailerOperatorId

	// no validation rules for CompanyOperatorId

	// no validation rules for OperatorId

	// no validation rules for Enabled

	if len(errors) > 0 {
		return VipConfigMultiError(errors)
	}

	return nil
}

// VipConfigMultiError is an error wrapping multiple validation errors returned
// by VipConfig.ValidateAll() if the designated constraints aren't met.
type VipConfigMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m VipConfigMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m VipConfigMultiError) AllErrors() []error { return m }

// VipConfigValidationError is the validation error returned by
// VipConfig.Validate if the designated constraints aren't met.
type VipConfigValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e VipConfigValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e VipConfigValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e VipConfigValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e VipConfigValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e VipConfigValidationError) ErrorName() string { return "VipConfigValidationError" }

// Error satisfies the builtin error interface
func (e VipConfigValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sVipConfig.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = VipConfigValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = VipConfigValidationError{}

// Validate checks the field values on GetVipConfigResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetVipConfigResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetVipConfigResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetVipConfigResponseMultiError, or nil if none found.
func (m *GetVipConfigResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetVipConfigResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetConfig()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetVipConfigResponseValidationError{
					field:  "Config",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetVipConfigResponseValidationError{
					field:  "Config",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetConfig()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetVipConfigResponseValidationError{
				field:  "Config",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetVipConfigResponseMultiError(errors)
	}

	return nil
}

// GetVipConfigResponseMultiError is an error wrapping multiple validation
// errors returned by GetVipConfigResponse.ValidateAll() if the designated
// constraints aren't met.
type GetVipConfigResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetVipConfigResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetVipConfigResponseMultiError) AllErrors() []error { return m }

// GetVipConfigResponseValidationError is the validation error returned by
// GetVipConfigResponse.Validate if the designated constraints aren't met.
type GetVipConfigResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetVipConfigResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetVipConfigResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetVipConfigResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetVipConfigResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetVipConfigResponseValidationError) ErrorName() string {
	return "GetVipConfigResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetVipConfigResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetVipConfigResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetVipConfigResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetVipConfigResponseValidationError{}
