// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v5.29.3
// source: backoffice/service/v1/backoffice_event.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BackofficeEvent_Event_FullMethodName = "/api.backoffice.service.v1.BackofficeEvent/Event"
)

// BackofficeEventClient is the client API for BackofficeEvent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BackofficeEventClient interface {
	Event(ctx context.Context, in *EventRequest, opts ...grpc.CallOption) (*EventResponse, error)
}

type backofficeEventClient struct {
	cc grpc.ClientConnInterface
}

func NewBackofficeEventClient(cc grpc.ClientConnInterface) BackofficeEventClient {
	return &backofficeEventClient{cc}
}

func (c *backofficeEventClient) Event(ctx context.Context, in *EventRequest, opts ...grpc.CallOption) (*EventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EventResponse)
	err := c.cc.Invoke(ctx, BackofficeEvent_Event_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BackofficeEventServer is the server API for BackofficeEvent service.
// All implementations must embed UnimplementedBackofficeEventServer
// for forward compatibility.
type BackofficeEventServer interface {
	Event(context.Context, *EventRequest) (*EventResponse, error)
	mustEmbedUnimplementedBackofficeEventServer()
}

// UnimplementedBackofficeEventServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBackofficeEventServer struct{}

func (UnimplementedBackofficeEventServer) Event(context.Context, *EventRequest) (*EventResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Event not implemented")
}
func (UnimplementedBackofficeEventServer) mustEmbedUnimplementedBackofficeEventServer() {}
func (UnimplementedBackofficeEventServer) testEmbeddedByValue()                         {}

// UnsafeBackofficeEventServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BackofficeEventServer will
// result in compilation errors.
type UnsafeBackofficeEventServer interface {
	mustEmbedUnimplementedBackofficeEventServer()
}

func RegisterBackofficeEventServer(s grpc.ServiceRegistrar, srv BackofficeEventServer) {
	// If the following call panics, it indicates UnimplementedBackofficeEventServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BackofficeEvent_ServiceDesc, srv)
}

func _BackofficeEvent_Event_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackofficeEventServer).Event(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BackofficeEvent_Event_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackofficeEventServer).Event(ctx, req.(*EventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BackofficeEvent_ServiceDesc is the grpc.ServiceDesc for BackofficeEvent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BackofficeEvent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.backoffice.service.v1.BackofficeEvent",
	HandlerType: (*BackofficeEventServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Event",
			Handler:    _BackofficeEvent_Event_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "backoffice/service/v1/backoffice_event.proto",
}
