// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v7.34.1
// source: backoffice/service/v1/backoffice_notification.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
	v1 "github.com/infigaming-com/meepo-api/push/service/v1"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationBackofficeNotificationCreateNotificationChannel = "/api.backoffice.service.v1.BackofficeNotification/CreateNotificationChannel"
const OperationBackofficeNotificationDeleteNotificationChannel = "/api.backoffice.service.v1.BackofficeNotification/DeleteNotificationChannel"
const OperationBackofficeNotificationGetNotificationChannel = "/api.backoffice.service.v1.BackofficeNotification/GetNotificationChannel"
const OperationBackofficeNotificationGetSupportedMessageTypes = "/api.backoffice.service.v1.BackofficeNotification/GetSupportedMessageTypes"
const OperationBackofficeNotificationListNotificationChannels = "/api.backoffice.service.v1.BackofficeNotification/ListNotificationChannels"
const OperationBackofficeNotificationListNotificationRules = "/api.backoffice.service.v1.BackofficeNotification/ListNotificationRules"
const OperationBackofficeNotificationSaveChannelRules = "/api.backoffice.service.v1.BackofficeNotification/SaveChannelRules"
const OperationBackofficeNotificationTestNotificationChannel = "/api.backoffice.service.v1.BackofficeNotification/TestNotificationChannel"
const OperationBackofficeNotificationUpdateNotificationChannel = "/api.backoffice.service.v1.BackofficeNotification/UpdateNotificationChannel"

type BackofficeNotificationHTTPServer interface {
	// CreateNotificationChannel Create a new notification channel.
	//
	// Creates a Telegram or Slack channel that can receive notification messages.
	// After creation, use SaveChannelRules to attach notification rules to this channel.
	//
	// ## Request body
	//
	// | Field | Type | Required | Description |
	// |-------|------|----------|-------------|
	// | target_operator_context | OperatorContext | No | Target operator. Defaults to logged-in operator |
	// | name | string | Yes | Display name for the channel |
	// | channel_type | ChannelType | Yes | `CHANNEL_TYPE_TELEGRAM` (1) or `CHANNEL_TYPE_SLACK` (2) |
	// | config | ChannelConfig | Yes | Channel-specific configuration (see below) |
	// | enabled | bool | No | Whether the channel is active. Default: false |
	//
	// ### ChannelConfig
	//
	// Provide **one of** the following based on `channel_type`:
	//
	// **Telegram** (`config.telegram`):
	// | Field | Type | Description |
	// |-------|------|-------------|
	// | bot_token | string | Telegram Bot API token |
	// | chat_id | string | Target chat/group ID |
	//
	// **Slack** (`config.slack`):
	// | Field | Type | Description |
	// |-------|------|-------------|
	// | webhook_url | string | Slack incoming webhook URL |
	//
	// ## Response
	//
	// | Field | Type | Description |
	// |-------|------|-------------|
	// | channel | NotificationChannel | The created channel with generated `id` and timestamps |
	//
	// ## Example
	//
	// ```json
	// // Request
	// {
	//   "name": "Risk Alerts - Telegram",
	//   "channel_type": 1,
	//   "config": {
	//     "telegram": {
	//       "bot_token": "123456:ABC-DEF...",
	//       "chat_id": "-1001234567890"
	//     }
	//   },
	//   "enabled": true
	// }
	//
	// // Response
	// {
	//   "channel": {
	//     "id": 42,
	//     "name": "Risk Alerts - Telegram",
	//     "channel_type": 1,
	//     "config": {
	//       "telegram": {
	//         "bot_token_masked": "123***DEF...",
	//         "chat_id": "-1001234567890"
	//       }
	//     },
	//     "enabled": true,
	//     "created_at": 1710000000,
	//     "updated_at": 1710000000,
	//     "is_inherited": false
	//   }
	// }
	// ```
	CreateNotificationChannel(context.Context, *v1.CreateNotificationChannelRequest) (*v1.CreateNotificationChannelResponse, error)
	// DeleteNotificationChannel Delete a notification channel and all its associated rules.
	//
	// ## Request body
	//
	// | Field | Type | Required | Description |
	// |-------|------|----------|-------------|
	// | target_operator_context | OperatorContext | No | Target operator. Defaults to logged-in operator |
	// | channel_id | int64 | Yes | Channel ID to delete |
	//
	// ## Response
	//
	// Empty on success.
	DeleteNotificationChannel(context.Context, *v1.DeleteNotificationChannelRequest) (*v1.DeleteNotificationChannelResponse, error)
	// GetNotificationChannel Get a specific notification channel by ID.
	//
	// ## Request body
	//
	// | Field | Type | Required | Description |
	// |-------|------|----------|-------------|
	// | target_operator_context | OperatorContext | No | Target operator. Defaults to logged-in operator |
	// | channel_id | int64 | Yes | Channel ID to retrieve |
	//
	// ## Response
	//
	// | Field | Type | Description |
	// |-------|------|-------------|
	// | channel | NotificationChannel | The channel details. Sensitive fields (bot_token, webhook_url) are masked |
	GetNotificationChannel(context.Context, *v1.GetNotificationChannelRequest) (*v1.GetNotificationChannelResponse, error)
	// GetSupportedMessageTypes Get supported message types for frontend dropdown.
	//
	// Returns the list of all available message types with display names,
	// useful for building UI dropdowns/selectors.
	//
	// ## Request body
	//
	// Empty — no parameters required.
	//
	// ## Response
	//
	// | Field | Type | Description |
	// |-------|------|-------------|
	// | message_types | MessageTypeInfo[] | List of supported message types |
	//
	// ### MessageTypeInfo
	//
	// | Field | Type | Description |
	// |-------|------|-------------|
	// | value | MessageType | Enum value |
	// | name | string | Enum name (e.g. `"MESSAGE_TYPE_LARGE_DEPOSIT"`) |
	// | display_name | string | Human-readable name (e.g. `"Large Deposit"`) |
	GetSupportedMessageTypes(context.Context, *v1.GetSupportedMessageTypesRequest) (*v1.GetSupportedMessageTypesResponse, error)
	// ListNotificationChannels List notification channels with pagination.
	//
	// Returns channels owned by or inherited to the current operator.
	// Supports filtering by channel type and enabled status.
	//
	// ## Request body
	//
	// | Field | Type | Required | Description |
	// |-------|------|----------|-------------|
	// | target_operator_context | OperatorContext | No | Target operator. Defaults to logged-in operator |
	// | channel_type | ChannelType | No | Filter by type (omit for all) |
	// | enabled | bool | No | Filter by enabled status (omit for all) |
	// | include_inherited | bool | No | If true, include channels from parent levels |
	// | page | int32 | No | Page number, starting from 1 |
	// | page_size | int32 | No | Items per page |
	//
	// ## Response
	//
	// | Field | Type | Description |
	// |-------|------|-------------|
	// | channels | NotificationChannel[] | List of channels |
	// | total | int32 | Total count matching filters |
	// | page | int32 | Current page |
	// | page_size | int32 | Items per page |
	ListNotificationChannels(context.Context, *v1.ListNotificationChannelsRequest) (*v1.ListNotificationChannelsResponse, error)
	// ListNotificationRules List notification rules with pagination.
	//
	// Returns rules matching the given filters. Supports filtering by message type,
	// enabled status, and channel.
	//
	// ## Request body
	//
	// | Field | Type | Required | Description |
	// |-------|------|----------|-------------|
	// | target_operator_context | OperatorContext | No | Target operator. Defaults to logged-in operator |
	// | message_type | MessageType | No | Filter by message type (omit for all) |
	// | enabled | bool | No | Filter by enabled status (omit for all) |
	// | include_inherited | bool | No | If true, include rules from parent levels |
	// | channel_id | int64 | No | Filter by channel (0 = all channels) |
	// | page | int32 | No | Page number, starting from 1 |
	// | page_size | int32 | No | Items per page |
	//
	// ## Response
	//
	// | Field | Type | Description |
	// |-------|------|-------------|
	// | rules | NotificationRule[] | List of rules |
	// | total | int32 | Total count matching filters |
	// | page | int32 | Current page |
	// | page_size | int32 | Items per page |
	ListNotificationRules(context.Context, *v1.ListNotificationRulesRequest) (*v1.ListNotificationRulesResponse, error)
	// SaveChannelRules Save all rules for a channel (batch create/update/delete).
	//
	// This is a full replacement operation for a channel's rules:
	// - Rules with `id = 0` are created as new rules
	// - Rules with `id > 0` are updated
	// - Existing rules NOT included in the request are deleted
	//
	// ## Request body
	//
	// | Field | Type | Required | Description |
	// |-------|------|----------|-------------|
	// | target_operator_context | OperatorContext | No | Target operator. Defaults to logged-in operator |
	// | channel_id | int64 | Yes | Channel to save rules for |
	// | rules | NotificationRuleInput[] | Yes | Full list of rules for this channel |
	//
	// ### NotificationRuleInput
	//
	// | Field | Type | Required | Description |
	// |-------|------|----------|-------------|
	// | id | int64 | No | `0` = create new, `>0` = update existing |
	// | name | string | Yes | Display name for the rule |
	// | message_type | MessageType | Yes | Event type to match (see enum above) |
	// | rule_type | RuleType | Yes | `RULE_TYPE_GENERIC` (1) or `RULE_TYPE_CURRENCY_THRESHOLD` (2) |
	// | currency_conditions | CurrencyCondition[] | No | Required when `rule_type = RULE_TYPE_CURRENCY_THRESHOLD` |
	// | enabled | bool | No | Whether the rule is active |
	//
	// ### CurrencyCondition
	//
	// | Field | Type | Description |
	// |-------|------|-------------|
	// | currency | string | Currency code, e.g. `"USD"`, `"BTC"`, or `"*"` (wildcard for all) |
	// | min_amount | string | Minimum amount threshold (decimal string, e.g. `"1000.00"`) |
	// | min_odds | string | Minimum odds threshold (for `MESSAGE_TYPE_LARGE_WIN` only) |
	//
	// ## Response
	//
	// | Field | Type | Description |
	// |-------|------|-------------|
	// | rules | NotificationRule[] | The saved rules with generated IDs and timestamps |
	//
	// ## Example
	//
	// ```json
	// // Request — set up large deposit + withdrawal alerts for a channel
	// {
	//   "channel_id": 42,
	//   "rules": [
	//     {
	//       "id": 0,
	//       "name": "Large USD Deposits",
	//       "message_type": 3,
	//       "rule_type": 2,
	//       "currency_conditions": [
	//         { "currency": "USD", "min_amount": "5000.00" },
	//         { "currency": "EUR", "min_amount": "4500.00" }
	//       ],
	//       "enabled": true
	//     },
	//     {
	//       "id": 0,
	//       "name": "All Withdrawals",
	//       "message_type": 1,
	//       "rule_type": 1,
	//       "enabled": true
	//     }
	//   ]
	// }
	// ```
	SaveChannelRules(context.Context, *v1.SaveChannelRulesRequest) (*v1.SaveChannelRulesResponse, error)
	// TestNotificationChannel Test a notification channel by sending a test message.
	//
	// Sends a test message through the channel to verify configuration is correct.
	// Does not require the channel to be enabled.
	//
	// ## Request body
	//
	// | Field | Type | Required | Description |
	// |-------|------|----------|-------------|
	// | target_operator_context | OperatorContext | No | Target operator. Defaults to logged-in operator |
	// | channel_id | int64 | Yes | Channel ID to test |
	// | test_message | string | No | Custom message to send. If empty, a default test message is used |
	//
	// ## Response
	//
	// | Field | Type | Description |
	// |-------|------|-------------|
	// | success | bool | Whether the test message was delivered successfully |
	// | error_message | string | Error details if delivery failed |
	TestNotificationChannel(context.Context, *v1.TestNotificationChannelRequest) (*v1.TestNotificationChannelResponse, error)
	// UpdateNotificationChannel Partially update a notification channel. Only provided fields are updated.
	//
	// ## Request body
	//
	// | Field | Type | Required | Description |
	// |-------|------|----------|-------------|
	// | target_operator_context | OperatorContext | No | Target operator. Defaults to logged-in operator |
	// | channel_id | int64 | Yes | Channel ID to update |
	// | name | string | No | New display name |
	// | config | ChannelConfig | No | New channel config (replaces existing) |
	// | enabled | bool | No | Enable or disable |
	//
	// ## Response
	//
	// Empty on success.
	UpdateNotificationChannel(context.Context, *v1.UpdateNotificationChannelRequest) (*v1.UpdateNotificationChannelResponse, error)
}

func RegisterBackofficeNotificationHTTPServer(s *http.Server, srv BackofficeNotificationHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/backoffice/notification/channel/create", _BackofficeNotification_CreateNotificationChannel0_HTTP_Handler(srv))
	r.POST("/v1/backoffice/notification/channel/list", _BackofficeNotification_ListNotificationChannels0_HTTP_Handler(srv))
	r.POST("/v1/backoffice/notification/channel/get", _BackofficeNotification_GetNotificationChannel0_HTTP_Handler(srv))
	r.POST("/v1/backoffice/notification/channel/update", _BackofficeNotification_UpdateNotificationChannel0_HTTP_Handler(srv))
	r.POST("/v1/backoffice/notification/channel/delete", _BackofficeNotification_DeleteNotificationChannel0_HTTP_Handler(srv))
	r.POST("/v1/backoffice/notification/channel/test", _BackofficeNotification_TestNotificationChannel0_HTTP_Handler(srv))
	r.POST("/v1/backoffice/notification/rule/save", _BackofficeNotification_SaveChannelRules0_HTTP_Handler(srv))
	r.POST("/v1/backoffice/notification/rule/list", _BackofficeNotification_ListNotificationRules0_HTTP_Handler(srv))
	r.POST("/v1/backoffice/notification/message-types", _BackofficeNotification_GetSupportedMessageTypes0_HTTP_Handler(srv))
}

func _BackofficeNotification_CreateNotificationChannel0_HTTP_Handler(srv BackofficeNotificationHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in v1.CreateNotificationChannelRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBackofficeNotificationCreateNotificationChannel)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateNotificationChannel(ctx, req.(*v1.CreateNotificationChannelRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*v1.CreateNotificationChannelResponse)
		return ctx.Result(200, reply)
	}
}

func _BackofficeNotification_ListNotificationChannels0_HTTP_Handler(srv BackofficeNotificationHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in v1.ListNotificationChannelsRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBackofficeNotificationListNotificationChannels)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListNotificationChannels(ctx, req.(*v1.ListNotificationChannelsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*v1.ListNotificationChannelsResponse)
		return ctx.Result(200, reply)
	}
}

func _BackofficeNotification_GetNotificationChannel0_HTTP_Handler(srv BackofficeNotificationHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in v1.GetNotificationChannelRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBackofficeNotificationGetNotificationChannel)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetNotificationChannel(ctx, req.(*v1.GetNotificationChannelRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*v1.GetNotificationChannelResponse)
		return ctx.Result(200, reply)
	}
}

func _BackofficeNotification_UpdateNotificationChannel0_HTTP_Handler(srv BackofficeNotificationHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in v1.UpdateNotificationChannelRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBackofficeNotificationUpdateNotificationChannel)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateNotificationChannel(ctx, req.(*v1.UpdateNotificationChannelRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*v1.UpdateNotificationChannelResponse)
		return ctx.Result(200, reply)
	}
}

func _BackofficeNotification_DeleteNotificationChannel0_HTTP_Handler(srv BackofficeNotificationHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in v1.DeleteNotificationChannelRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBackofficeNotificationDeleteNotificationChannel)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteNotificationChannel(ctx, req.(*v1.DeleteNotificationChannelRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*v1.DeleteNotificationChannelResponse)
		return ctx.Result(200, reply)
	}
}

func _BackofficeNotification_TestNotificationChannel0_HTTP_Handler(srv BackofficeNotificationHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in v1.TestNotificationChannelRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBackofficeNotificationTestNotificationChannel)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.TestNotificationChannel(ctx, req.(*v1.TestNotificationChannelRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*v1.TestNotificationChannelResponse)
		return ctx.Result(200, reply)
	}
}

func _BackofficeNotification_SaveChannelRules0_HTTP_Handler(srv BackofficeNotificationHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in v1.SaveChannelRulesRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBackofficeNotificationSaveChannelRules)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SaveChannelRules(ctx, req.(*v1.SaveChannelRulesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*v1.SaveChannelRulesResponse)
		return ctx.Result(200, reply)
	}
}

func _BackofficeNotification_ListNotificationRules0_HTTP_Handler(srv BackofficeNotificationHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in v1.ListNotificationRulesRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBackofficeNotificationListNotificationRules)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListNotificationRules(ctx, req.(*v1.ListNotificationRulesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*v1.ListNotificationRulesResponse)
		return ctx.Result(200, reply)
	}
}

func _BackofficeNotification_GetSupportedMessageTypes0_HTTP_Handler(srv BackofficeNotificationHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in v1.GetSupportedMessageTypesRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBackofficeNotificationGetSupportedMessageTypes)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetSupportedMessageTypes(ctx, req.(*v1.GetSupportedMessageTypesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*v1.GetSupportedMessageTypesResponse)
		return ctx.Result(200, reply)
	}
}

type BackofficeNotificationHTTPClient interface {
	// CreateNotificationChannel Create a new notification channel.
	//
	// Creates a Telegram or Slack channel that can receive notification messages.
	// After creation, use SaveChannelRules to attach notification rules to this channel.
	//
	// ## Request body
	//
	// | Field | Type | Required | Description |
	// |-------|------|----------|-------------|
	// | target_operator_context | OperatorContext | No | Target operator. Defaults to logged-in operator |
	// | name | string | Yes | Display name for the channel |
	// | channel_type | ChannelType | Yes | `CHANNEL_TYPE_TELEGRAM` (1) or `CHANNEL_TYPE_SLACK` (2) |
	// | config | ChannelConfig | Yes | Channel-specific configuration (see below) |
	// | enabled | bool | No | Whether the channel is active. Default: false |
	//
	// ### ChannelConfig
	//
	// Provide **one of** the following based on `channel_type`:
	//
	// **Telegram** (`config.telegram`):
	// | Field | Type | Description |
	// |-------|------|-------------|
	// | bot_token | string | Telegram Bot API token |
	// | chat_id | string | Target chat/group ID |
	//
	// **Slack** (`config.slack`):
	// | Field | Type | Description |
	// |-------|------|-------------|
	// | webhook_url | string | Slack incoming webhook URL |
	//
	// ## Response
	//
	// | Field | Type | Description |
	// |-------|------|-------------|
	// | channel | NotificationChannel | The created channel with generated `id` and timestamps |
	//
	// ## Example
	//
	// ```json
	// // Request
	// {
	//   "name": "Risk Alerts - Telegram",
	//   "channel_type": 1,
	//   "config": {
	//     "telegram": {
	//       "bot_token": "123456:ABC-DEF...",
	//       "chat_id": "-1001234567890"
	//     }
	//   },
	//   "enabled": true
	// }
	//
	// // Response
	// {
	//   "channel": {
	//     "id": 42,
	//     "name": "Risk Alerts - Telegram",
	//     "channel_type": 1,
	//     "config": {
	//       "telegram": {
	//         "bot_token_masked": "123***DEF...",
	//         "chat_id": "-1001234567890"
	//       }
	//     },
	//     "enabled": true,
	//     "created_at": 1710000000,
	//     "updated_at": 1710000000,
	//     "is_inherited": false
	//   }
	// }
	// ```
	CreateNotificationChannel(ctx context.Context, req *v1.CreateNotificationChannelRequest, opts ...http.CallOption) (rsp *v1.CreateNotificationChannelResponse, err error)
	// DeleteNotificationChannel Delete a notification channel and all its associated rules.
	//
	// ## Request body
	//
	// | Field | Type | Required | Description |
	// |-------|------|----------|-------------|
	// | target_operator_context | OperatorContext | No | Target operator. Defaults to logged-in operator |
	// | channel_id | int64 | Yes | Channel ID to delete |
	//
	// ## Response
	//
	// Empty on success.
	DeleteNotificationChannel(ctx context.Context, req *v1.DeleteNotificationChannelRequest, opts ...http.CallOption) (rsp *v1.DeleteNotificationChannelResponse, err error)
	// GetNotificationChannel Get a specific notification channel by ID.
	//
	// ## Request body
	//
	// | Field | Type | Required | Description |
	// |-------|------|----------|-------------|
	// | target_operator_context | OperatorContext | No | Target operator. Defaults to logged-in operator |
	// | channel_id | int64 | Yes | Channel ID to retrieve |
	//
	// ## Response
	//
	// | Field | Type | Description |
	// |-------|------|-------------|
	// | channel | NotificationChannel | The channel details. Sensitive fields (bot_token, webhook_url) are masked |
	GetNotificationChannel(ctx context.Context, req *v1.GetNotificationChannelRequest, opts ...http.CallOption) (rsp *v1.GetNotificationChannelResponse, err error)
	// GetSupportedMessageTypes Get supported message types for frontend dropdown.
	//
	// Returns the list of all available message types with display names,
	// useful for building UI dropdowns/selectors.
	//
	// ## Request body
	//
	// Empty — no parameters required.
	//
	// ## Response
	//
	// | Field | Type | Description |
	// |-------|------|-------------|
	// | message_types | MessageTypeInfo[] | List of supported message types |
	//
	// ### MessageTypeInfo
	//
	// | Field | Type | Description |
	// |-------|------|-------------|
	// | value | MessageType | Enum value |
	// | name | string | Enum name (e.g. `"MESSAGE_TYPE_LARGE_DEPOSIT"`) |
	// | display_name | string | Human-readable name (e.g. `"Large Deposit"`) |
	GetSupportedMessageTypes(ctx context.Context, req *v1.GetSupportedMessageTypesRequest, opts ...http.CallOption) (rsp *v1.GetSupportedMessageTypesResponse, err error)
	// ListNotificationChannels List notification channels with pagination.
	//
	// Returns channels owned by or inherited to the current operator.
	// Supports filtering by channel type and enabled status.
	//
	// ## Request body
	//
	// | Field | Type | Required | Description |
	// |-------|------|----------|-------------|
	// | target_operator_context | OperatorContext | No | Target operator. Defaults to logged-in operator |
	// | channel_type | ChannelType | No | Filter by type (omit for all) |
	// | enabled | bool | No | Filter by enabled status (omit for all) |
	// | include_inherited | bool | No | If true, include channels from parent levels |
	// | page | int32 | No | Page number, starting from 1 |
	// | page_size | int32 | No | Items per page |
	//
	// ## Response
	//
	// | Field | Type | Description |
	// |-------|------|-------------|
	// | channels | NotificationChannel[] | List of channels |
	// | total | int32 | Total count matching filters |
	// | page | int32 | Current page |
	// | page_size | int32 | Items per page |
	ListNotificationChannels(ctx context.Context, req *v1.ListNotificationChannelsRequest, opts ...http.CallOption) (rsp *v1.ListNotificationChannelsResponse, err error)
	// ListNotificationRules List notification rules with pagination.
	//
	// Returns rules matching the given filters. Supports filtering by message type,
	// enabled status, and channel.
	//
	// ## Request body
	//
	// | Field | Type | Required | Description |
	// |-------|------|----------|-------------|
	// | target_operator_context | OperatorContext | No | Target operator. Defaults to logged-in operator |
	// | message_type | MessageType | No | Filter by message type (omit for all) |
	// | enabled | bool | No | Filter by enabled status (omit for all) |
	// | include_inherited | bool | No | If true, include rules from parent levels |
	// | channel_id | int64 | No | Filter by channel (0 = all channels) |
	// | page | int32 | No | Page number, starting from 1 |
	// | page_size | int32 | No | Items per page |
	//
	// ## Response
	//
	// | Field | Type | Description |
	// |-------|------|-------------|
	// | rules | NotificationRule[] | List of rules |
	// | total | int32 | Total count matching filters |
	// | page | int32 | Current page |
	// | page_size | int32 | Items per page |
	ListNotificationRules(ctx context.Context, req *v1.ListNotificationRulesRequest, opts ...http.CallOption) (rsp *v1.ListNotificationRulesResponse, err error)
	// SaveChannelRules Save all rules for a channel (batch create/update/delete).
	//
	// This is a full replacement operation for a channel's rules:
	// - Rules with `id = 0` are created as new rules
	// - Rules with `id > 0` are updated
	// - Existing rules NOT included in the request are deleted
	//
	// ## Request body
	//
	// | Field | Type | Required | Description |
	// |-------|------|----------|-------------|
	// | target_operator_context | OperatorContext | No | Target operator. Defaults to logged-in operator |
	// | channel_id | int64 | Yes | Channel to save rules for |
	// | rules | NotificationRuleInput[] | Yes | Full list of rules for this channel |
	//
	// ### NotificationRuleInput
	//
	// | Field | Type | Required | Description |
	// |-------|------|----------|-------------|
	// | id | int64 | No | `0` = create new, `>0` = update existing |
	// | name | string | Yes | Display name for the rule |
	// | message_type | MessageType | Yes | Event type to match (see enum above) |
	// | rule_type | RuleType | Yes | `RULE_TYPE_GENERIC` (1) or `RULE_TYPE_CURRENCY_THRESHOLD` (2) |
	// | currency_conditions | CurrencyCondition[] | No | Required when `rule_type = RULE_TYPE_CURRENCY_THRESHOLD` |
	// | enabled | bool | No | Whether the rule is active |
	//
	// ### CurrencyCondition
	//
	// | Field | Type | Description |
	// |-------|------|-------------|
	// | currency | string | Currency code, e.g. `"USD"`, `"BTC"`, or `"*"` (wildcard for all) |
	// | min_amount | string | Minimum amount threshold (decimal string, e.g. `"1000.00"`) |
	// | min_odds | string | Minimum odds threshold (for `MESSAGE_TYPE_LARGE_WIN` only) |
	//
	// ## Response
	//
	// | Field | Type | Description |
	// |-------|------|-------------|
	// | rules | NotificationRule[] | The saved rules with generated IDs and timestamps |
	//
	// ## Example
	//
	// ```json
	// // Request — set up large deposit + withdrawal alerts for a channel
	// {
	//   "channel_id": 42,
	//   "rules": [
	//     {
	//       "id": 0,
	//       "name": "Large USD Deposits",
	//       "message_type": 3,
	//       "rule_type": 2,
	//       "currency_conditions": [
	//         { "currency": "USD", "min_amount": "5000.00" },
	//         { "currency": "EUR", "min_amount": "4500.00" }
	//       ],
	//       "enabled": true
	//     },
	//     {
	//       "id": 0,
	//       "name": "All Withdrawals",
	//       "message_type": 1,
	//       "rule_type": 1,
	//       "enabled": true
	//     }
	//   ]
	// }
	// ```
	SaveChannelRules(ctx context.Context, req *v1.SaveChannelRulesRequest, opts ...http.CallOption) (rsp *v1.SaveChannelRulesResponse, err error)
	// TestNotificationChannel Test a notification channel by sending a test message.
	//
	// Sends a test message through the channel to verify configuration is correct.
	// Does not require the channel to be enabled.
	//
	// ## Request body
	//
	// | Field | Type | Required | Description |
	// |-------|------|----------|-------------|
	// | target_operator_context | OperatorContext | No | Target operator. Defaults to logged-in operator |
	// | channel_id | int64 | Yes | Channel ID to test |
	// | test_message | string | No | Custom message to send. If empty, a default test message is used |
	//
	// ## Response
	//
	// | Field | Type | Description |
	// |-------|------|-------------|
	// | success | bool | Whether the test message was delivered successfully |
	// | error_message | string | Error details if delivery failed |
	TestNotificationChannel(ctx context.Context, req *v1.TestNotificationChannelRequest, opts ...http.CallOption) (rsp *v1.TestNotificationChannelResponse, err error)
	// UpdateNotificationChannel Partially update a notification channel. Only provided fields are updated.
	//
	// ## Request body
	//
	// | Field | Type | Required | Description |
	// |-------|------|----------|-------------|
	// | target_operator_context | OperatorContext | No | Target operator. Defaults to logged-in operator |
	// | channel_id | int64 | Yes | Channel ID to update |
	// | name | string | No | New display name |
	// | config | ChannelConfig | No | New channel config (replaces existing) |
	// | enabled | bool | No | Enable or disable |
	//
	// ## Response
	//
	// Empty on success.
	UpdateNotificationChannel(ctx context.Context, req *v1.UpdateNotificationChannelRequest, opts ...http.CallOption) (rsp *v1.UpdateNotificationChannelResponse, err error)
}

type BackofficeNotificationHTTPClientImpl struct {
	cc *http.Client
}

func NewBackofficeNotificationHTTPClient(client *http.Client) BackofficeNotificationHTTPClient {
	return &BackofficeNotificationHTTPClientImpl{client}
}

// CreateNotificationChannel Create a new notification channel.
//
// Creates a Telegram or Slack channel that can receive notification messages.
// After creation, use SaveChannelRules to attach notification rules to this channel.
//
// ## Request body
//
// | Field | Type | Required | Description |
// |-------|------|----------|-------------|
// | target_operator_context | OperatorContext | No | Target operator. Defaults to logged-in operator |
// | name | string | Yes | Display name for the channel |
// | channel_type | ChannelType | Yes | `CHANNEL_TYPE_TELEGRAM` (1) or `CHANNEL_TYPE_SLACK` (2) |
// | config | ChannelConfig | Yes | Channel-specific configuration (see below) |
// | enabled | bool | No | Whether the channel is active. Default: false |
//
// ### ChannelConfig
//
// Provide **one of** the following based on `channel_type`:
//
// **Telegram** (`config.telegram`):
// | Field | Type | Description |
// |-------|------|-------------|
// | bot_token | string | Telegram Bot API token |
// | chat_id | string | Target chat/group ID |
//
// **Slack** (`config.slack`):
// | Field | Type | Description |
// |-------|------|-------------|
// | webhook_url | string | Slack incoming webhook URL |
//
// ## Response
//
// | Field | Type | Description |
// |-------|------|-------------|
// | channel | NotificationChannel | The created channel with generated `id` and timestamps |
//
// ## Example
//
// ```json
// // Request
// {
//   "name": "Risk Alerts - Telegram",
//   "channel_type": 1,
//   "config": {
//     "telegram": {
//       "bot_token": "123456:ABC-DEF...",
//       "chat_id": "-1001234567890"
//     }
//   },
//   "enabled": true
// }
//
// // Response
// {
//   "channel": {
//     "id": 42,
//     "name": "Risk Alerts - Telegram",
//     "channel_type": 1,
//     "config": {
//       "telegram": {
//         "bot_token_masked": "123***DEF...",
//         "chat_id": "-1001234567890"
//       }
//     },
//     "enabled": true,
//     "created_at": 1710000000,
//     "updated_at": 1710000000,
//     "is_inherited": false
//   }
// }
// ```
func (c *BackofficeNotificationHTTPClientImpl) CreateNotificationChannel(ctx context.Context, in *v1.CreateNotificationChannelRequest, opts ...http.CallOption) (*v1.CreateNotificationChannelResponse, error) {
	var out v1.CreateNotificationChannelResponse
	pattern := "/v1/backoffice/notification/channel/create"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationBackofficeNotificationCreateNotificationChannel))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// DeleteNotificationChannel Delete a notification channel and all its associated rules.
//
// ## Request body
//
// | Field | Type | Required | Description |
// |-------|------|----------|-------------|
// | target_operator_context | OperatorContext | No | Target operator. Defaults to logged-in operator |
// | channel_id | int64 | Yes | Channel ID to delete |
//
// ## Response
//
// Empty on success.
func (c *BackofficeNotificationHTTPClientImpl) DeleteNotificationChannel(ctx context.Context, in *v1.DeleteNotificationChannelRequest, opts ...http.CallOption) (*v1.DeleteNotificationChannelResponse, error) {
	var out v1.DeleteNotificationChannelResponse
	pattern := "/v1/backoffice/notification/channel/delete"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationBackofficeNotificationDeleteNotificationChannel))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetNotificationChannel Get a specific notification channel by ID.
//
// ## Request body
//
// | Field | Type | Required | Description |
// |-------|------|----------|-------------|
// | target_operator_context | OperatorContext | No | Target operator. Defaults to logged-in operator |
// | channel_id | int64 | Yes | Channel ID to retrieve |
//
// ## Response
//
// | Field | Type | Description |
// |-------|------|-------------|
// | channel | NotificationChannel | The channel details. Sensitive fields (bot_token, webhook_url) are masked |
func (c *BackofficeNotificationHTTPClientImpl) GetNotificationChannel(ctx context.Context, in *v1.GetNotificationChannelRequest, opts ...http.CallOption) (*v1.GetNotificationChannelResponse, error) {
	var out v1.GetNotificationChannelResponse
	pattern := "/v1/backoffice/notification/channel/get"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationBackofficeNotificationGetNotificationChannel))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetSupportedMessageTypes Get supported message types for frontend dropdown.
//
// Returns the list of all available message types with display names,
// useful for building UI dropdowns/selectors.
//
// ## Request body
//
// Empty — no parameters required.
//
// ## Response
//
// | Field | Type | Description |
// |-------|------|-------------|
// | message_types | MessageTypeInfo[] | List of supported message types |
//
// ### MessageTypeInfo
//
// | Field | Type | Description |
// |-------|------|-------------|
// | value | MessageType | Enum value |
// | name | string | Enum name (e.g. `"MESSAGE_TYPE_LARGE_DEPOSIT"`) |
// | display_name | string | Human-readable name (e.g. `"Large Deposit"`) |
func (c *BackofficeNotificationHTTPClientImpl) GetSupportedMessageTypes(ctx context.Context, in *v1.GetSupportedMessageTypesRequest, opts ...http.CallOption) (*v1.GetSupportedMessageTypesResponse, error) {
	var out v1.GetSupportedMessageTypesResponse
	pattern := "/v1/backoffice/notification/message-types"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationBackofficeNotificationGetSupportedMessageTypes))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListNotificationChannels List notification channels with pagination.
//
// Returns channels owned by or inherited to the current operator.
// Supports filtering by channel type and enabled status.
//
// ## Request body
//
// | Field | Type | Required | Description |
// |-------|------|----------|-------------|
// | target_operator_context | OperatorContext | No | Target operator. Defaults to logged-in operator |
// | channel_type | ChannelType | No | Filter by type (omit for all) |
// | enabled | bool | No | Filter by enabled status (omit for all) |
// | include_inherited | bool | No | If true, include channels from parent levels |
// | page | int32 | No | Page number, starting from 1 |
// | page_size | int32 | No | Items per page |
//
// ## Response
//
// | Field | Type | Description |
// |-------|------|-------------|
// | channels | NotificationChannel[] | List of channels |
// | total | int32 | Total count matching filters |
// | page | int32 | Current page |
// | page_size | int32 | Items per page |
func (c *BackofficeNotificationHTTPClientImpl) ListNotificationChannels(ctx context.Context, in *v1.ListNotificationChannelsRequest, opts ...http.CallOption) (*v1.ListNotificationChannelsResponse, error) {
	var out v1.ListNotificationChannelsResponse
	pattern := "/v1/backoffice/notification/channel/list"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationBackofficeNotificationListNotificationChannels))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListNotificationRules List notification rules with pagination.
//
// Returns rules matching the given filters. Supports filtering by message type,
// enabled status, and channel.
//
// ## Request body
//
// | Field | Type | Required | Description |
// |-------|------|----------|-------------|
// | target_operator_context | OperatorContext | No | Target operator. Defaults to logged-in operator |
// | message_type | MessageType | No | Filter by message type (omit for all) |
// | enabled | bool | No | Filter by enabled status (omit for all) |
// | include_inherited | bool | No | If true, include rules from parent levels |
// | channel_id | int64 | No | Filter by channel (0 = all channels) |
// | page | int32 | No | Page number, starting from 1 |
// | page_size | int32 | No | Items per page |
//
// ## Response
//
// | Field | Type | Description |
// |-------|------|-------------|
// | rules | NotificationRule[] | List of rules |
// | total | int32 | Total count matching filters |
// | page | int32 | Current page |
// | page_size | int32 | Items per page |
func (c *BackofficeNotificationHTTPClientImpl) ListNotificationRules(ctx context.Context, in *v1.ListNotificationRulesRequest, opts ...http.CallOption) (*v1.ListNotificationRulesResponse, error) {
	var out v1.ListNotificationRulesResponse
	pattern := "/v1/backoffice/notification/rule/list"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationBackofficeNotificationListNotificationRules))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// SaveChannelRules Save all rules for a channel (batch create/update/delete).
//
// This is a full replacement operation for a channel's rules:
// - Rules with `id = 0` are created as new rules
// - Rules with `id > 0` are updated
// - Existing rules NOT included in the request are deleted
//
// ## Request body
//
// | Field | Type | Required | Description |
// |-------|------|----------|-------------|
// | target_operator_context | OperatorContext | No | Target operator. Defaults to logged-in operator |
// | channel_id | int64 | Yes | Channel to save rules for |
// | rules | NotificationRuleInput[] | Yes | Full list of rules for this channel |
//
// ### NotificationRuleInput
//
// | Field | Type | Required | Description |
// |-------|------|----------|-------------|
// | id | int64 | No | `0` = create new, `>0` = update existing |
// | name | string | Yes | Display name for the rule |
// | message_type | MessageType | Yes | Event type to match (see enum above) |
// | rule_type | RuleType | Yes | `RULE_TYPE_GENERIC` (1) or `RULE_TYPE_CURRENCY_THRESHOLD` (2) |
// | currency_conditions | CurrencyCondition[] | No | Required when `rule_type = RULE_TYPE_CURRENCY_THRESHOLD` |
// | enabled | bool | No | Whether the rule is active |
//
// ### CurrencyCondition
//
// | Field | Type | Description |
// |-------|------|-------------|
// | currency | string | Currency code, e.g. `"USD"`, `"BTC"`, or `"*"` (wildcard for all) |
// | min_amount | string | Minimum amount threshold (decimal string, e.g. `"1000.00"`) |
// | min_odds | string | Minimum odds threshold (for `MESSAGE_TYPE_LARGE_WIN` only) |
//
// ## Response
//
// | Field | Type | Description |
// |-------|------|-------------|
// | rules | NotificationRule[] | The saved rules with generated IDs and timestamps |
//
// ## Example
//
// ```json
// // Request — set up large deposit + withdrawal alerts for a channel
// {
//   "channel_id": 42,
//   "rules": [
//     {
//       "id": 0,
//       "name": "Large USD Deposits",
//       "message_type": 3,
//       "rule_type": 2,
//       "currency_conditions": [
//         { "currency": "USD", "min_amount": "5000.00" },
//         { "currency": "EUR", "min_amount": "4500.00" }
//       ],
//       "enabled": true
//     },
//     {
//       "id": 0,
//       "name": "All Withdrawals",
//       "message_type": 1,
//       "rule_type": 1,
//       "enabled": true
//     }
//   ]
// }
// ```
func (c *BackofficeNotificationHTTPClientImpl) SaveChannelRules(ctx context.Context, in *v1.SaveChannelRulesRequest, opts ...http.CallOption) (*v1.SaveChannelRulesResponse, error) {
	var out v1.SaveChannelRulesResponse
	pattern := "/v1/backoffice/notification/rule/save"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationBackofficeNotificationSaveChannelRules))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// TestNotificationChannel Test a notification channel by sending a test message.
//
// Sends a test message through the channel to verify configuration is correct.
// Does not require the channel to be enabled.
//
// ## Request body
//
// | Field | Type | Required | Description |
// |-------|------|----------|-------------|
// | target_operator_context | OperatorContext | No | Target operator. Defaults to logged-in operator |
// | channel_id | int64 | Yes | Channel ID to test |
// | test_message | string | No | Custom message to send. If empty, a default test message is used |
//
// ## Response
//
// | Field | Type | Description |
// |-------|------|-------------|
// | success | bool | Whether the test message was delivered successfully |
// | error_message | string | Error details if delivery failed |
func (c *BackofficeNotificationHTTPClientImpl) TestNotificationChannel(ctx context.Context, in *v1.TestNotificationChannelRequest, opts ...http.CallOption) (*v1.TestNotificationChannelResponse, error) {
	var out v1.TestNotificationChannelResponse
	pattern := "/v1/backoffice/notification/channel/test"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationBackofficeNotificationTestNotificationChannel))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdateNotificationChannel Partially update a notification channel. Only provided fields are updated.
//
// ## Request body
//
// | Field | Type | Required | Description |
// |-------|------|----------|-------------|
// | target_operator_context | OperatorContext | No | Target operator. Defaults to logged-in operator |
// | channel_id | int64 | Yes | Channel ID to update |
// | name | string | No | New display name |
// | config | ChannelConfig | No | New channel config (replaces existing) |
// | enabled | bool | No | Enable or disable |
//
// ## Response
//
// Empty on success.
func (c *BackofficeNotificationHTTPClientImpl) UpdateNotificationChannel(ctx context.Context, in *v1.UpdateNotificationChannelRequest, opts ...http.CallOption) (*v1.UpdateNotificationChannelResponse, error) {
	var out v1.UpdateNotificationChannelResponse
	pattern := "/v1/backoffice/notification/channel/update"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationBackofficeNotificationUpdateNotificationChannel))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
