// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: backoffice/service/v1/error_reason.proto

package v1

import (
	_ "github.com/go-kratos/kratos/v2/errors"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorReason int32

const (
	ErrorReason_UNSPECIFIED                        ErrorReason = 0
	ErrorReason_CALL_WALLET_SERVICE_FAILED         ErrorReason = 60000
	ErrorReason_OPERATOR_IDS_NOT_FOUND_IN_CONTEXT  ErrorReason = 60001
	ErrorReason_USER_INFO_NOT_FOUND_IN_CONTEXT     ErrorReason = 60002
	ErrorReason_REPORT_TIME_RANGE_ERROR            ErrorReason = 60003
	ErrorReason_REPORT_GET_DATA_ERROR              ErrorReason = 60004
	ErrorReason_OPERATOR_CONTEXT_PERMISSION_DENIED ErrorReason = 60005
	ErrorReason_CLOUDFLARE_INVALID_REQUEST         ErrorReason = 61000
	ErrorReason_CLOUDFLARE_PERMISSION_DENIED       ErrorReason = 61001
	ErrorReason_CLOUDFLARE_CONFIG_UNAVAILABLE      ErrorReason = 61002
	ErrorReason_CLOUDFLARE_OPERATOR_NOT_FOUND      ErrorReason = 61003
	ErrorReason_CLOUDFLARE_PURGE_FAILED            ErrorReason = 61004
	// 2FA related errors
	ErrorReason_MFA_NOT_ENABLED             ErrorReason = 62001
	ErrorReason_MFA_ALREADY_ENABLED         ErrorReason = 62002
	ErrorReason_INVALID_2FA_CODE            ErrorReason = 62003
	ErrorReason_TEMP_TOKEN_EXPIRED          ErrorReason = 62004
	ErrorReason_TEMP_TOKEN_INVALID          ErrorReason = 62005
	ErrorReason_MFA_REQUIRED                ErrorReason = 62006
	ErrorReason_PERMISSION_DENIED_RESET_2FA ErrorReason = 62007
	ErrorReason_MFA_RATE_LIMITED            ErrorReason = 62008
)

// Enum value maps for ErrorReason.
var (
	ErrorReason_name = map[int32]string{
		0:     "UNSPECIFIED",
		60000: "CALL_WALLET_SERVICE_FAILED",
		60001: "OPERATOR_IDS_NOT_FOUND_IN_CONTEXT",
		60002: "USER_INFO_NOT_FOUND_IN_CONTEXT",
		60003: "REPORT_TIME_RANGE_ERROR",
		60004: "REPORT_GET_DATA_ERROR",
		60005: "OPERATOR_CONTEXT_PERMISSION_DENIED",
		61000: "CLOUDFLARE_INVALID_REQUEST",
		61001: "CLOUDFLARE_PERMISSION_DENIED",
		61002: "CLOUDFLARE_CONFIG_UNAVAILABLE",
		61003: "CLOUDFLARE_OPERATOR_NOT_FOUND",
		61004: "CLOUDFLARE_PURGE_FAILED",
		62001: "MFA_NOT_ENABLED",
		62002: "MFA_ALREADY_ENABLED",
		62003: "INVALID_2FA_CODE",
		62004: "TEMP_TOKEN_EXPIRED",
		62005: "TEMP_TOKEN_INVALID",
		62006: "MFA_REQUIRED",
		62007: "PERMISSION_DENIED_RESET_2FA",
		62008: "MFA_RATE_LIMITED",
	}
	ErrorReason_value = map[string]int32{
		"UNSPECIFIED":                        0,
		"CALL_WALLET_SERVICE_FAILED":         60000,
		"OPERATOR_IDS_NOT_FOUND_IN_CONTEXT":  60001,
		"USER_INFO_NOT_FOUND_IN_CONTEXT":     60002,
		"REPORT_TIME_RANGE_ERROR":            60003,
		"REPORT_GET_DATA_ERROR":              60004,
		"OPERATOR_CONTEXT_PERMISSION_DENIED": 60005,
		"CLOUDFLARE_INVALID_REQUEST":         61000,
		"CLOUDFLARE_PERMISSION_DENIED":       61001,
		"CLOUDFLARE_CONFIG_UNAVAILABLE":      61002,
		"CLOUDFLARE_OPERATOR_NOT_FOUND":      61003,
		"CLOUDFLARE_PURGE_FAILED":            61004,
		"MFA_NOT_ENABLED":                    62001,
		"MFA_ALREADY_ENABLED":                62002,
		"INVALID_2FA_CODE":                   62003,
		"TEMP_TOKEN_EXPIRED":                 62004,
		"TEMP_TOKEN_INVALID":                 62005,
		"MFA_REQUIRED":                       62006,
		"PERMISSION_DENIED_RESET_2FA":        62007,
		"MFA_RATE_LIMITED":                   62008,
	}
)

func (x ErrorReason) Enum() *ErrorReason {
	p := new(ErrorReason)
	*p = x
	return p
}

func (x ErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_backoffice_service_v1_error_reason_proto_enumTypes[0].Descriptor()
}

func (ErrorReason) Type() protoreflect.EnumType {
	return &file_backoffice_service_v1_error_reason_proto_enumTypes[0]
}

func (x ErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorReason.Descriptor instead.
func (ErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_backoffice_service_v1_error_reason_proto_rawDescGZIP(), []int{0}
}

var File_backoffice_service_v1_error_reason_proto protoreflect.FileDescriptor

const file_backoffice_service_v1_error_reason_proto_rawDesc = "" +
	"\n" +
	"(backoffice/service/v1/error_reason.proto\x12\x19api.backoffice.service.v1\x1a\x13errors/errors.proto*\xa7\x05\n" +
	"\vErrorReason\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12 \n" +
	"\x1aCALL_WALLET_SERVICE_FAILED\x10\xe0\xd4\x03\x12'\n" +
	"!OPERATOR_IDS_NOT_FOUND_IN_CONTEXT\x10\xe1\xd4\x03\x12$\n" +
	"\x1eUSER_INFO_NOT_FOUND_IN_CONTEXT\x10\xe2\xd4\x03\x12\x1d\n" +
	"\x17REPORT_TIME_RANGE_ERROR\x10\xe3\xd4\x03\x12\x1b\n" +
	"\x15REPORT_GET_DATA_ERROR\x10\xe4\xd4\x03\x12(\n" +
	"\"OPERATOR_CONTEXT_PERMISSION_DENIED\x10\xe5\xd4\x03\x12 \n" +
	"\x1aCLOUDFLARE_INVALID_REQUEST\x10\xc8\xdc\x03\x12\"\n" +
	"\x1cCLOUDFLARE_PERMISSION_DENIED\x10\xc9\xdc\x03\x12#\n" +
	"\x1dCLOUDFLARE_CONFIG_UNAVAILABLE\x10\xca\xdc\x03\x12#\n" +
	"\x1dCLOUDFLARE_OPERATOR_NOT_FOUND\x10\xcb\xdc\x03\x12\x1d\n" +
	"\x17CLOUDFLARE_PURGE_FAILED\x10\xcc\xdc\x03\x12\x1b\n" +
	"\x0fMFA_NOT_ENABLED\x10\xb1\xe4\x03\x1a\x04\xa8E\x90\x03\x12\x1f\n" +
	"\x13MFA_ALREADY_ENABLED\x10\xb2\xe4\x03\x1a\x04\xa8E\x90\x03\x12\x1c\n" +
	"\x10INVALID_2FA_CODE\x10\xb3\xe4\x03\x1a\x04\xa8E\x91\x03\x12\x1e\n" +
	"\x12TEMP_TOKEN_EXPIRED\x10\xb4\xe4\x03\x1a\x04\xa8E\x91\x03\x12\x1e\n" +
	"\x12TEMP_TOKEN_INVALID\x10\xb5\xe4\x03\x1a\x04\xa8E\x91\x03\x12\x18\n" +
	"\fMFA_REQUIRED\x10\xb6\xe4\x03\x1a\x04\xa8E\x93\x03\x12'\n" +
	"\x1bPERMISSION_DENIED_RESET_2FA\x10\xb7\xe4\x03\x1a\x04\xa8E\x93\x03\x12\x1c\n" +
	"\x10MFA_RATE_LIMITED\x10\xb8\xe4\x03\x1a\x04\xa8E\xad\x03\x1a\x04\xa0E\xf4\x03B[\n" +
	"\x19api.backoffice.service.v1P\x01Z<github.com/infigaming-com/meepo-api/backoffice/service/v1;v1b\x06proto3"

var (
	file_backoffice_service_v1_error_reason_proto_rawDescOnce sync.Once
	file_backoffice_service_v1_error_reason_proto_rawDescData []byte
)

func file_backoffice_service_v1_error_reason_proto_rawDescGZIP() []byte {
	file_backoffice_service_v1_error_reason_proto_rawDescOnce.Do(func() {
		file_backoffice_service_v1_error_reason_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_backoffice_service_v1_error_reason_proto_rawDesc), len(file_backoffice_service_v1_error_reason_proto_rawDesc)))
	})
	return file_backoffice_service_v1_error_reason_proto_rawDescData
}

var file_backoffice_service_v1_error_reason_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_backoffice_service_v1_error_reason_proto_goTypes = []any{
	(ErrorReason)(0), // 0: api.backoffice.service.v1.ErrorReason
}
var file_backoffice_service_v1_error_reason_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_backoffice_service_v1_error_reason_proto_init() }
func file_backoffice_service_v1_error_reason_proto_init() {
	if File_backoffice_service_v1_error_reason_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_backoffice_service_v1_error_reason_proto_rawDesc), len(file_backoffice_service_v1_error_reason_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_backoffice_service_v1_error_reason_proto_goTypes,
		DependencyIndexes: file_backoffice_service_v1_error_reason_proto_depIdxs,
		EnumInfos:         file_backoffice_service_v1_error_reason_proto_enumTypes,
	}.Build()
	File_backoffice_service_v1_error_reason_proto = out.File
	file_backoffice_service_v1_error_reason_proto_goTypes = nil
	file_backoffice_service_v1_error_reason_proto_depIdxs = nil
}
