kind: Gateway
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: meepo-gateway
  namespace: meepo-dev
spec:
  gatewayClassName: gke-l7-regional-external-managed
  listeners:
  - name: meepoapi-xyz-https
    protocol: HTTPS
    port: 443
    hostname: "dev.meepoapi.xyz"
    tls:
      mode: Terminate
      certificateRefs:
      - name: meepoapi-xyz-tls
        namespace: meepo-dev
  addresses:
  - type: NamedAddress
    value: gke-meepo-dev-ingress-ip
