apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: meepoapi-xyz-routes
  namespace: meepo-dev
spec:
  parentRefs:
  - name: meepo-gateway
    namespace: meepo-dev
  hostnames:
  - "dev.meepoapi.xyz"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: "/v1/user"
    backendRefs:
    - name: user-svc
      port: 8000
      weight: 1
  - matches:
    - path:
        type: PathPrefix
        value: "/v1/operator"
    backendRefs:
    - name: operator-svc
      port: 8000
      weight: 1
  - matches:
    - path:
        type: PathPrefix
        value: "/v1/system"
    backendRefs:
    - name: system-svc
      port: 8000
      weight: 1
  - matches:
    - path:
        type: PathPrefix
        value: "/v1/game"
    backendRefs:
    - name: game-svc
      port: 8000
      weight: 1