// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v5.29.3
// source: push/service/v1/push.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Push_SendEmail_FullMethodName               = "/api.push.service.v1.Push/SendEmail"
	Push_GetNotificationStats_FullMethodName    = "/api.push.service.v1.Push/GetNotificationStats"
	Push_GetThirdPartyFeeStats_FullMethodName   = "/api.push.service.v1.Push/GetThirdPartyFeeStats"
	Push_UpdateBetTickerConfig_FullMethodName   = "/api.push.service.v1.Push/UpdateBetTickerConfig"
	Push_ListBetTickerConfig_FullMethodName     = "/api.push.service.v1.Push/ListBetTickerConfig"
	Push_SendWebPush_FullMethodName             = "/api.push.service.v1.Push/SendWebPush"
	Push_RegisterWebPushDevice_FullMethodName   = "/api.push.service.v1.Push/RegisterWebPushDevice"
	Push_UnregisterWebPushDevice_FullMethodName = "/api.push.service.v1.Push/UnregisterWebPushDevice"
)

// PushClient is the client API for Push service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PushClient interface {
	SendEmail(ctx context.Context, in *SendEmailRequest, opts ...grpc.CallOption) (*SendEmailResponse, error)
	// Get notification statistics for specified operators within a time range
	// Returns notification counts grouped by operator ID
	GetNotificationStats(ctx context.Context, in *GetNotificationStatsRequest, opts ...grpc.CallOption) (*GetNotificationStatsResponse, error)
	// Get third-party fee statistics (EMAIL + SMS/WhatsApp/Voice) for billing
	GetThirdPartyFeeStats(ctx context.Context, in *GetThirdPartyFeeStatsRequest, opts ...grpc.CallOption) (*GetThirdPartyFeeStatsResponse, error)
	// BetTicker Config APIs
	UpdateBetTickerConfig(ctx context.Context, in *UpdateBetTickerConfigRequest, opts ...grpc.CallOption) (*UpdateBetTickerConfigResponse, error)
	ListBetTickerConfig(ctx context.Context, in *ListBetTickerConfigRequest, opts ...grpc.CallOption) (*ListBetTickerConfigResponse, error)
	// Web Push APIs
	SendWebPush(ctx context.Context, in *SendWebPushRequest, opts ...grpc.CallOption) (*SendWebPushResponse, error)
	RegisterWebPushDevice(ctx context.Context, in *RegisterWebPushDeviceRequest, opts ...grpc.CallOption) (*RegisterWebPushDeviceResponse, error)
	UnregisterWebPushDevice(ctx context.Context, in *UnregisterWebPushDeviceRequest, opts ...grpc.CallOption) (*UnregisterWebPushDeviceResponse, error)
}

type pushClient struct {
	cc grpc.ClientConnInterface
}

func NewPushClient(cc grpc.ClientConnInterface) PushClient {
	return &pushClient{cc}
}

func (c *pushClient) SendEmail(ctx context.Context, in *SendEmailRequest, opts ...grpc.CallOption) (*SendEmailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendEmailResponse)
	err := c.cc.Invoke(ctx, Push_SendEmail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pushClient) GetNotificationStats(ctx context.Context, in *GetNotificationStatsRequest, opts ...grpc.CallOption) (*GetNotificationStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNotificationStatsResponse)
	err := c.cc.Invoke(ctx, Push_GetNotificationStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pushClient) GetThirdPartyFeeStats(ctx context.Context, in *GetThirdPartyFeeStatsRequest, opts ...grpc.CallOption) (*GetThirdPartyFeeStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetThirdPartyFeeStatsResponse)
	err := c.cc.Invoke(ctx, Push_GetThirdPartyFeeStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pushClient) UpdateBetTickerConfig(ctx context.Context, in *UpdateBetTickerConfigRequest, opts ...grpc.CallOption) (*UpdateBetTickerConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateBetTickerConfigResponse)
	err := c.cc.Invoke(ctx, Push_UpdateBetTickerConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pushClient) ListBetTickerConfig(ctx context.Context, in *ListBetTickerConfigRequest, opts ...grpc.CallOption) (*ListBetTickerConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBetTickerConfigResponse)
	err := c.cc.Invoke(ctx, Push_ListBetTickerConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pushClient) SendWebPush(ctx context.Context, in *SendWebPushRequest, opts ...grpc.CallOption) (*SendWebPushResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendWebPushResponse)
	err := c.cc.Invoke(ctx, Push_SendWebPush_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pushClient) RegisterWebPushDevice(ctx context.Context, in *RegisterWebPushDeviceRequest, opts ...grpc.CallOption) (*RegisterWebPushDeviceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterWebPushDeviceResponse)
	err := c.cc.Invoke(ctx, Push_RegisterWebPushDevice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pushClient) UnregisterWebPushDevice(ctx context.Context, in *UnregisterWebPushDeviceRequest, opts ...grpc.CallOption) (*UnregisterWebPushDeviceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnregisterWebPushDeviceResponse)
	err := c.cc.Invoke(ctx, Push_UnregisterWebPushDevice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PushServer is the server API for Push service.
// All implementations must embed UnimplementedPushServer
// for forward compatibility.
type PushServer interface {
	SendEmail(context.Context, *SendEmailRequest) (*SendEmailResponse, error)
	// Get notification statistics for specified operators within a time range
	// Returns notification counts grouped by operator ID
	GetNotificationStats(context.Context, *GetNotificationStatsRequest) (*GetNotificationStatsResponse, error)
	// Get third-party fee statistics (EMAIL + SMS/WhatsApp/Voice) for billing
	GetThirdPartyFeeStats(context.Context, *GetThirdPartyFeeStatsRequest) (*GetThirdPartyFeeStatsResponse, error)
	// BetTicker Config APIs
	UpdateBetTickerConfig(context.Context, *UpdateBetTickerConfigRequest) (*UpdateBetTickerConfigResponse, error)
	ListBetTickerConfig(context.Context, *ListBetTickerConfigRequest) (*ListBetTickerConfigResponse, error)
	// Web Push APIs
	SendWebPush(context.Context, *SendWebPushRequest) (*SendWebPushResponse, error)
	RegisterWebPushDevice(context.Context, *RegisterWebPushDeviceRequest) (*RegisterWebPushDeviceResponse, error)
	UnregisterWebPushDevice(context.Context, *UnregisterWebPushDeviceRequest) (*UnregisterWebPushDeviceResponse, error)
	mustEmbedUnimplementedPushServer()
}

// UnimplementedPushServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPushServer struct{}

func (UnimplementedPushServer) SendEmail(context.Context, *SendEmailRequest) (*SendEmailResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendEmail not implemented")
}
func (UnimplementedPushServer) GetNotificationStats(context.Context, *GetNotificationStatsRequest) (*GetNotificationStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNotificationStats not implemented")
}
func (UnimplementedPushServer) GetThirdPartyFeeStats(context.Context, *GetThirdPartyFeeStatsRequest) (*GetThirdPartyFeeStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetThirdPartyFeeStats not implemented")
}
func (UnimplementedPushServer) UpdateBetTickerConfig(context.Context, *UpdateBetTickerConfigRequest) (*UpdateBetTickerConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateBetTickerConfig not implemented")
}
func (UnimplementedPushServer) ListBetTickerConfig(context.Context, *ListBetTickerConfigRequest) (*ListBetTickerConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListBetTickerConfig not implemented")
}
func (UnimplementedPushServer) SendWebPush(context.Context, *SendWebPushRequest) (*SendWebPushResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendWebPush not implemented")
}
func (UnimplementedPushServer) RegisterWebPushDevice(context.Context, *RegisterWebPushDeviceRequest) (*RegisterWebPushDeviceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterWebPushDevice not implemented")
}
func (UnimplementedPushServer) UnregisterWebPushDevice(context.Context, *UnregisterWebPushDeviceRequest) (*UnregisterWebPushDeviceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnregisterWebPushDevice not implemented")
}
func (UnimplementedPushServer) mustEmbedUnimplementedPushServer() {}
func (UnimplementedPushServer) testEmbeddedByValue()              {}

// UnsafePushServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PushServer will
// result in compilation errors.
type UnsafePushServer interface {
	mustEmbedUnimplementedPushServer()
}

func RegisterPushServer(s grpc.ServiceRegistrar, srv PushServer) {
	// If the following call panics, it indicates UnimplementedPushServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Push_ServiceDesc, srv)
}

func _Push_SendEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PushServer).SendEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Push_SendEmail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PushServer).SendEmail(ctx, req.(*SendEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Push_GetNotificationStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNotificationStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PushServer).GetNotificationStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Push_GetNotificationStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PushServer).GetNotificationStats(ctx, req.(*GetNotificationStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Push_GetThirdPartyFeeStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetThirdPartyFeeStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PushServer).GetThirdPartyFeeStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Push_GetThirdPartyFeeStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PushServer).GetThirdPartyFeeStats(ctx, req.(*GetThirdPartyFeeStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Push_UpdateBetTickerConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBetTickerConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PushServer).UpdateBetTickerConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Push_UpdateBetTickerConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PushServer).UpdateBetTickerConfig(ctx, req.(*UpdateBetTickerConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Push_ListBetTickerConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBetTickerConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PushServer).ListBetTickerConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Push_ListBetTickerConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PushServer).ListBetTickerConfig(ctx, req.(*ListBetTickerConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Push_SendWebPush_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendWebPushRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PushServer).SendWebPush(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Push_SendWebPush_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PushServer).SendWebPush(ctx, req.(*SendWebPushRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Push_RegisterWebPushDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterWebPushDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PushServer).RegisterWebPushDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Push_RegisterWebPushDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PushServer).RegisterWebPushDevice(ctx, req.(*RegisterWebPushDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Push_UnregisterWebPushDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnregisterWebPushDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PushServer).UnregisterWebPushDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Push_UnregisterWebPushDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PushServer).UnregisterWebPushDevice(ctx, req.(*UnregisterWebPushDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Push_ServiceDesc is the grpc.ServiceDesc for Push service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Push_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.push.service.v1.Push",
	HandlerType: (*PushServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendEmail",
			Handler:    _Push_SendEmail_Handler,
		},
		{
			MethodName: "GetNotificationStats",
			Handler:    _Push_GetNotificationStats_Handler,
		},
		{
			MethodName: "GetThirdPartyFeeStats",
			Handler:    _Push_GetThirdPartyFeeStats_Handler,
		},
		{
			MethodName: "UpdateBetTickerConfig",
			Handler:    _Push_UpdateBetTickerConfig_Handler,
		},
		{
			MethodName: "ListBetTickerConfig",
			Handler:    _Push_ListBetTickerConfig_Handler,
		},
		{
			MethodName: "SendWebPush",
			Handler:    _Push_SendWebPush_Handler,
		},
		{
			MethodName: "RegisterWebPushDevice",
			Handler:    _Push_RegisterWebPushDevice_Handler,
		},
		{
			MethodName: "UnregisterWebPushDevice",
			Handler:    _Push_UnregisterWebPushDevice_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "push/service/v1/push.proto",
}
