// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.6
// source: payment/service/v1/payment.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request to get payment method list
type GetPaymentMethodListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentMethodListRequest) Reset() {
	*x = GetPaymentMethodListRequest{}
	mi := &file_payment_service_v1_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentMethodListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentMethodListRequest) ProtoMessage() {}

func (x *GetPaymentMethodListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_v1_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentMethodListRequest.ProtoReflect.Descriptor instead.
func (*GetPaymentMethodListRequest) Descriptor() ([]byte, []int) {
	return file_payment_service_v1_payment_proto_rawDescGZIP(), []int{0}
}

// Details of a single payment method
type PaymentMethodInfo struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Id            string                     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Currency      string                     `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	Country       string                     `protobuf:"bytes,3,opt,name=country,proto3" json:"country,omitempty"`
	PaymentMethod string                     `protobuf:"bytes,4,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	KeySchema     map[string]*structpb.Value `protobuf:"bytes,5,rep,name=key_schema,json=keySchema,proto3" json:"key_schema,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Stores schema for required fields of the payment method
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentMethodInfo) Reset() {
	*x = PaymentMethodInfo{}
	mi := &file_payment_service_v1_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentMethodInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentMethodInfo) ProtoMessage() {}

func (x *PaymentMethodInfo) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_v1_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentMethodInfo.ProtoReflect.Descriptor instead.
func (*PaymentMethodInfo) Descriptor() ([]byte, []int) {
	return file_payment_service_v1_payment_proto_rawDescGZIP(), []int{1}
}

func (x *PaymentMethodInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PaymentMethodInfo) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *PaymentMethodInfo) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *PaymentMethodInfo) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *PaymentMethodInfo) GetKeySchema() map[string]*structpb.Value {
	if x != nil {
		return x.KeySchema
	}
	return nil
}

// Response for payment method list
type GetPaymentMethodListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	Code          int32                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Data          []*PaymentMethodInfo   `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentMethodListResponse) Reset() {
	*x = GetPaymentMethodListResponse{}
	mi := &file_payment_service_v1_payment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentMethodListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentMethodListResponse) ProtoMessage() {}

func (x *GetPaymentMethodListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_v1_payment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentMethodListResponse.ProtoReflect.Descriptor instead.
func (*GetPaymentMethodListResponse) Descriptor() ([]byte, []int) {
	return file_payment_service_v1_payment_proto_rawDescGZIP(), []int{2}
}

func (x *GetPaymentMethodListResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GetPaymentMethodListResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetPaymentMethodListResponse) GetData() []*PaymentMethodInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

// Request to create a payment channel
type CreatePaymentChannelRequest struct {
	state           protoimpl.MessageState     `protogen:"open.v1"`
	MerchantId      string                     `protobuf:"bytes,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	PaymentMethodId string                     `protobuf:"bytes,2,opt,name=payment_method_id,json=paymentMethodId,proto3" json:"payment_method_id,omitempty"`
	Key             map[string]*structpb.Value `protobuf:"bytes,3,rep,name=key,proto3" json:"key,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Stores configuration fields for the payment channel
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreatePaymentChannelRequest) Reset() {
	*x = CreatePaymentChannelRequest{}
	mi := &file_payment_service_v1_payment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentChannelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentChannelRequest) ProtoMessage() {}

func (x *CreatePaymentChannelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_v1_payment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentChannelRequest.ProtoReflect.Descriptor instead.
func (*CreatePaymentChannelRequest) Descriptor() ([]byte, []int) {
	return file_payment_service_v1_payment_proto_rawDescGZIP(), []int{3}
}

func (x *CreatePaymentChannelRequest) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *CreatePaymentChannelRequest) GetPaymentMethodId() string {
	if x != nil {
		return x.PaymentMethodId
	}
	return ""
}

func (x *CreatePaymentChannelRequest) GetKey() map[string]*structpb.Value {
	if x != nil {
		return x.Key
	}
	return nil
}

// Response for channel creation
type CreatePaymentChannelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	Code          int32                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Data          *ChannelData           `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePaymentChannelResponse) Reset() {
	*x = CreatePaymentChannelResponse{}
	mi := &file_payment_service_v1_payment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentChannelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentChannelResponse) ProtoMessage() {}

func (x *CreatePaymentChannelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_v1_payment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentChannelResponse.ProtoReflect.Descriptor instead.
func (*CreatePaymentChannelResponse) Descriptor() ([]byte, []int) {
	return file_payment_service_v1_payment_proto_rawDescGZIP(), []int{4}
}

func (x *CreatePaymentChannelResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *CreatePaymentChannelResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CreatePaymentChannelResponse) GetData() *ChannelData {
	if x != nil {
		return x.Data
	}
	return nil
}

// Channel data structure
type ChannelData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelData) Reset() {
	*x = ChannelData{}
	mi := &file_payment_service_v1_payment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelData) ProtoMessage() {}

func (x *ChannelData) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_v1_payment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelData.ProtoReflect.Descriptor instead.
func (*ChannelData) Descriptor() ([]byte, []int) {
	return file_payment_service_v1_payment_proto_rawDescGZIP(), []int{5}
}

func (x *ChannelData) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

// Request to get payment channel list
type GetPaymentChannelListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerchantId    string                 `protobuf:"bytes,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentChannelListRequest) Reset() {
	*x = GetPaymentChannelListRequest{}
	mi := &file_payment_service_v1_payment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentChannelListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentChannelListRequest) ProtoMessage() {}

func (x *GetPaymentChannelListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_v1_payment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentChannelListRequest.ProtoReflect.Descriptor instead.
func (*GetPaymentChannelListRequest) Descriptor() ([]byte, []int) {
	return file_payment_service_v1_payment_proto_rawDescGZIP(), []int{6}
}

func (x *GetPaymentChannelListRequest) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

// Payment channel information
type PaymentChannelInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ChannelId       string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	MerchantId      string                 `protobuf:"bytes,2,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	PaymentMethodId string                 `protobuf:"bytes,3,opt,name=payment_method_id,json=paymentMethodId,proto3" json:"payment_method_id,omitempty"`
	PaymentMethod   string                 `protobuf:"bytes,4,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	Currency        string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	Country         string                 `protobuf:"bytes,6,opt,name=country,proto3" json:"country,omitempty"`
	Status          int32                  `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PaymentChannelInfo) Reset() {
	*x = PaymentChannelInfo{}
	mi := &file_payment_service_v1_payment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentChannelInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentChannelInfo) ProtoMessage() {}

func (x *PaymentChannelInfo) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_v1_payment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentChannelInfo.ProtoReflect.Descriptor instead.
func (*PaymentChannelInfo) Descriptor() ([]byte, []int) {
	return file_payment_service_v1_payment_proto_rawDescGZIP(), []int{7}
}

func (x *PaymentChannelInfo) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *PaymentChannelInfo) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *PaymentChannelInfo) GetPaymentMethodId() string {
	if x != nil {
		return x.PaymentMethodId
	}
	return ""
}

func (x *PaymentChannelInfo) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *PaymentChannelInfo) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *PaymentChannelInfo) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *PaymentChannelInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *PaymentChannelInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *PaymentChannelInfo) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Response for payment channel list
type GetPaymentChannelListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	Code          int32                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Data          []*PaymentChannelInfo  `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentChannelListResponse) Reset() {
	*x = GetPaymentChannelListResponse{}
	mi := &file_payment_service_v1_payment_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentChannelListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentChannelListResponse) ProtoMessage() {}

func (x *GetPaymentChannelListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_v1_payment_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentChannelListResponse.ProtoReflect.Descriptor instead.
func (*GetPaymentChannelListResponse) Descriptor() ([]byte, []int) {
	return file_payment_service_v1_payment_proto_rawDescGZIP(), []int{8}
}

func (x *GetPaymentChannelListResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GetPaymentChannelListResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetPaymentChannelListResponse) GetData() []*PaymentChannelInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_payment_service_v1_payment_proto protoreflect.FileDescriptor

const file_payment_service_v1_payment_proto_rawDesc = "" +
	"\n" +
	" payment/service/v1/payment.proto\x12\x12payment.service.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x1d\n" +
	"\x1bGetPaymentMethodListRequest\"\xab\x02\n" +
	"\x11PaymentMethodInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrency\x12\x18\n" +
	"\acountry\x18\x03 \x01(\tR\acountry\x12%\n" +
	"\x0epayment_method\x18\x04 \x01(\tR\rpaymentMethod\x12S\n" +
	"\n" +
	"key_schema\x18\x05 \x03(\v24.payment.service.v1.PaymentMethodInfo.KeySchemaEntryR\tkeySchema\x1aT\n" +
	"\x0eKeySchemaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\x05value:\x028\x01\"\x7f\n" +
	"\x1cGetPaymentMethodListResponse\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x05R\x04code\x129\n" +
	"\x04data\x18\x03 \x03(\v2%.payment.service.v1.PaymentMethodInfoR\x04data\"\x86\x02\n" +
	"\x1bCreatePaymentChannelRequest\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\tR\n" +
	"merchantId\x12*\n" +
	"\x11payment_method_id\x18\x02 \x01(\tR\x0fpaymentMethodId\x12J\n" +
	"\x03key\x18\x03 \x03(\v28.payment.service.v1.CreatePaymentChannelRequest.KeyEntryR\x03key\x1aN\n" +
	"\bKeyEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\x05value:\x028\x01\"y\n" +
	"\x1cCreatePaymentChannelResponse\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x05R\x04code\x123\n" +
	"\x04data\x18\x03 \x01(\v2\x1f.payment.service.v1.ChannelDataR\x04data\",\n" +
	"\vChannelData\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\"?\n" +
	"\x1cGetPaymentChannelListRequest\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\tR\n" +
	"merchantId\"\xeb\x02\n" +
	"\x12PaymentChannelInfo\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\x12\x1f\n" +
	"\vmerchant_id\x18\x02 \x01(\tR\n" +
	"merchantId\x12*\n" +
	"\x11payment_method_id\x18\x03 \x01(\tR\x0fpaymentMethodId\x12%\n" +
	"\x0epayment_method\x18\x04 \x01(\tR\rpaymentMethod\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12\x18\n" +
	"\acountry\x18\x06 \x01(\tR\acountry\x12\x16\n" +
	"\x06status\x18\a \x01(\x05R\x06status\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x81\x01\n" +
	"\x1dGetPaymentChannelListResponse\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x05R\x04code\x12:\n" +
	"\x04data\x18\x03 \x03(\v2&.payment.service.v1.PaymentChannelInfoR\x04data2\xf3\x03\n" +
	"\aPayment\x12\x9e\x01\n" +
	"\x14GetPaymentMethodList\x12/.payment.service.v1.GetPaymentMethodListRequest\x1a0.payment.service.v1.GetPaymentMethodListResponse\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/api/payment/method/list\x12\xa1\x01\n" +
	"\x14CreatePaymentChannel\x12/.payment.service.v1.CreatePaymentChannelRequest\x1a0.payment.service.v1.CreatePaymentChannelResponse\"&\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/api/payment/channel/create\x12\xa2\x01\n" +
	"\x15GetPaymentChannelList\x120.payment.service.v1.GetPaymentChannelListRequest\x1a1.payment.service.v1.GetPaymentChannelListResponse\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/api/payment/channel/listBU\n" +
	"\x16api.payment.service.v1P\x01Z9github.com/infigaming-com/meepo-api/payment/service/v1;v1b\x06proto3"

var (
	file_payment_service_v1_payment_proto_rawDescOnce sync.Once
	file_payment_service_v1_payment_proto_rawDescData []byte
)

func file_payment_service_v1_payment_proto_rawDescGZIP() []byte {
	file_payment_service_v1_payment_proto_rawDescOnce.Do(func() {
		file_payment_service_v1_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_payment_service_v1_payment_proto_rawDesc), len(file_payment_service_v1_payment_proto_rawDesc)))
	})
	return file_payment_service_v1_payment_proto_rawDescData
}

var file_payment_service_v1_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_payment_service_v1_payment_proto_goTypes = []any{
	(*GetPaymentMethodListRequest)(nil),   // 0: payment.service.v1.GetPaymentMethodListRequest
	(*PaymentMethodInfo)(nil),             // 1: payment.service.v1.PaymentMethodInfo
	(*GetPaymentMethodListResponse)(nil),  // 2: payment.service.v1.GetPaymentMethodListResponse
	(*CreatePaymentChannelRequest)(nil),   // 3: payment.service.v1.CreatePaymentChannelRequest
	(*CreatePaymentChannelResponse)(nil),  // 4: payment.service.v1.CreatePaymentChannelResponse
	(*ChannelData)(nil),                   // 5: payment.service.v1.ChannelData
	(*GetPaymentChannelListRequest)(nil),  // 6: payment.service.v1.GetPaymentChannelListRequest
	(*PaymentChannelInfo)(nil),            // 7: payment.service.v1.PaymentChannelInfo
	(*GetPaymentChannelListResponse)(nil), // 8: payment.service.v1.GetPaymentChannelListResponse
	nil,                                   // 9: payment.service.v1.PaymentMethodInfo.KeySchemaEntry
	nil,                                   // 10: payment.service.v1.CreatePaymentChannelRequest.KeyEntry
	(*timestamppb.Timestamp)(nil),         // 11: google.protobuf.Timestamp
	(*structpb.Value)(nil),                // 12: google.protobuf.Value
}
var file_payment_service_v1_payment_proto_depIdxs = []int32{
	9,  // 0: payment.service.v1.PaymentMethodInfo.key_schema:type_name -> payment.service.v1.PaymentMethodInfo.KeySchemaEntry
	1,  // 1: payment.service.v1.GetPaymentMethodListResponse.data:type_name -> payment.service.v1.PaymentMethodInfo
	10, // 2: payment.service.v1.CreatePaymentChannelRequest.key:type_name -> payment.service.v1.CreatePaymentChannelRequest.KeyEntry
	5,  // 3: payment.service.v1.CreatePaymentChannelResponse.data:type_name -> payment.service.v1.ChannelData
	11, // 4: payment.service.v1.PaymentChannelInfo.created_at:type_name -> google.protobuf.Timestamp
	11, // 5: payment.service.v1.PaymentChannelInfo.updated_at:type_name -> google.protobuf.Timestamp
	7,  // 6: payment.service.v1.GetPaymentChannelListResponse.data:type_name -> payment.service.v1.PaymentChannelInfo
	12, // 7: payment.service.v1.PaymentMethodInfo.KeySchemaEntry.value:type_name -> google.protobuf.Value
	12, // 8: payment.service.v1.CreatePaymentChannelRequest.KeyEntry.value:type_name -> google.protobuf.Value
	0,  // 9: payment.service.v1.Payment.GetPaymentMethodList:input_type -> payment.service.v1.GetPaymentMethodListRequest
	3,  // 10: payment.service.v1.Payment.CreatePaymentChannel:input_type -> payment.service.v1.CreatePaymentChannelRequest
	6,  // 11: payment.service.v1.Payment.GetPaymentChannelList:input_type -> payment.service.v1.GetPaymentChannelListRequest
	2,  // 12: payment.service.v1.Payment.GetPaymentMethodList:output_type -> payment.service.v1.GetPaymentMethodListResponse
	4,  // 13: payment.service.v1.Payment.CreatePaymentChannel:output_type -> payment.service.v1.CreatePaymentChannelResponse
	8,  // 14: payment.service.v1.Payment.GetPaymentChannelList:output_type -> payment.service.v1.GetPaymentChannelListResponse
	12, // [12:15] is the sub-list for method output_type
	9,  // [9:12] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_payment_service_v1_payment_proto_init() }
func file_payment_service_v1_payment_proto_init() {
	if File_payment_service_v1_payment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_payment_service_v1_payment_proto_rawDesc), len(file_payment_service_v1_payment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_payment_service_v1_payment_proto_goTypes,
		DependencyIndexes: file_payment_service_v1_payment_proto_depIdxs,
		MessageInfos:      file_payment_service_v1_payment_proto_msgTypes,
	}.Build()
	File_payment_service_v1_payment_proto = out.File
	file_payment_service_v1_payment_proto_goTypes = nil
	file_payment_service_v1_payment_proto_depIdxs = nil
}
